import { existsSync, promises as fs } from 'fs'
import { basename, dirname, join, relative, resolve, sep } from 'path'
import { spawn, type ChildProcess } from 'child_process'
import { buildAddonPackageManifest } from '../shared/templates'
import { DEV_TASKS, type DevArtifact, type DevModuleCatalogStatus, type DevModuleLock, type DevModuleLockStatus, type DevModuleWorkspaceMap, type DevModuleWorkspaceStatus, type DevRuntimeLauncherStatus, type DevSetupResult, type DevTaskId, type DevTaskRun, type DevTaskStopResult, type DevToolchainStatus, type DevWorkspaceFileStatus, type DevWorkspaceMode, type DevWorkspaceOptions, type DevWorkspaceState } from '../shared/devWorkspace'
import { resolveProjectModulePlan, type EchoModuleCatalogResult, type EchoModuleRecord, type ProjectModulePlan } from '../shared/moduleCatalog'
import { buildNeoForgeModsToml } from '../shared/neoforgeMetadata'
import { MODULE_READY_TASKS, PREVIEW_RUNTIME_TASKS, moduleReadinessDisabledReason, previewRuntimeDisabledReason } from '../shared/previewRuntime'
import type { AddonManifest, Runtime } from '../shared/types'
import { packageAddon } from './packageService'
import { readManifest } from './fsService'
import { listEchoModules } from './moduleCatalogService'

const STUDIO_MARKER = 'Generated by ECHO Studio'
const GRADLE_VERSION = '9.1.0'
const GRADLE_DISTRIBUTION_URL = `https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip`
const MODULE_READY_TASK_SET = new Set<DevTaskId>(MODULE_READY_TASKS)
const PREVIEW_RUNTIME_TASK_SET = new Set<DevTaskId>(PREVIEW_RUNTIME_TASKS)

interface RunningDevProcess {
  child: ChildProcess
  taskId: DevTaskId
  command: string
  cwd: string
  logPath: string
  startedAt: string
  stopping: boolean
}

const runningDevProcesses = new Map<string, RunningDevProcess>()

async function exists(path: string): Promise<boolean> {
  try {
    await fs.access(path)
    return true
  } catch {
    return false
  }
}

async function readText(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf8')
  } catch {
    return ''
  }
}

async function readModuleLock(path: string): Promise<DevModuleLock | null> {
  try {
    const parsed = JSON.parse(await fs.readFile(path, 'utf8')) as Partial<DevModuleLock>
    return parsed.schemaVersion === 'echo.studio.modules.lock.v1' ? parsed as DevModuleLock : null
  } catch {
    return null
  }
}

async function readModuleWorkspace(path: string): Promise<DevModuleWorkspaceMap | null> {
  try {
    const parsed = JSON.parse(await fs.readFile(path, 'utf8')) as Partial<DevModuleWorkspaceMap>
    return parsed.schemaVersion === 'echo.studio.modules.workspace.v1' ? parsed as DevModuleWorkspaceMap : null
  } catch {
    return null
  }
}

async function writeIfAllowed(path: string, content: string, force: boolean, written: string[], skipped: string[]): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true })
  if (!force && await exists(path)) {
    skipped.push(path)
    return
  }
  await fs.writeFile(path, content, 'utf8')
  written.push(path)
}

async function writeGenerated(path: string, content: string, written: string[]): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, content, 'utf8')
  written.push(path)
}

function localId(manifest: AddonManifest): string {
  return manifest.id.includes(':') ? manifest.id.split(':')[1] : manifest.id
}

function moduleTaskReadinessReason(state: DevWorkspaceState, label: string): string | null {
  if (!state.moduleLock.upToDate) return 'Refresh Dev Workspace so generated module locks match the current manifest.'
  if (!state.moduleWorkspace.upToDate) return 'Refresh Dev Workspace so local module source map matches the current manifest.'
  return moduleReadinessDisabledReason(state, `running ${label}`)
}

async function assertDevTaskReady(projectPath: string, task: (typeof DEV_TASKS)[number]): Promise<void> {
  const needsGradle = task.id.startsWith('gradle:')
  const needsPreviewRuntime = PREVIEW_RUNTIME_TASK_SET.has(task.id)
  const needsModuleReady = MODULE_READY_TASK_SET.has(task.id)
  if (!needsGradle && !needsPreviewRuntime && !needsModuleReady) return

  const state = await inspectDevWorkspace(projectPath)
  let reason: string | null = null
  if (needsPreviewRuntime) {
    reason = previewRuntimeDisabledReason(task.id, state, true)
  } else if (needsGradle) {
    if (!state.gradleReady) reason = 'Set up a Gradle workspace first.'
    else if (!state.toolchain.javaAvailable) reason = `Install Java ${state.toolchain.requiredJavaVersion} or add it to PATH.`
    else if (!state.toolchain.javaMeetsRequirement) reason = `Use Java ${state.toolchain.requiredJavaVersion} for this generated workspace.`
    else if (!state.toolchain.gradleAvailable) reason = 'Run Dev Workspace setup to generate the pinned Gradle launcher or install Gradle.'
  }
  if (!reason && needsModuleReady) reason = moduleTaskReadinessReason(state, task.label)
  if (reason) throw new Error(reason)
}

function className(manifest: AddonManifest): string {
  return localId(manifest)
    .split(/[_-]/g)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join('') + 'Module'
}

function packagePath(manifest: AddonManifest): string {
  return `studio/generated/${manifest.namespace.replace(/[^a-z0-9_]/gi, '').toLowerCase()}/${localId(manifest).replace(/[^a-z0-9_]/gi, '').toLowerCase()}`.replace(/\//g, '/')
}

function artifactKind(name: string): DevArtifact['kind'] {
  if (name.endsWith('.echo-addon')) return 'echo-addon'
  if (name.endsWith('.jar')) return 'jar'
  if (name.endsWith('.json')) return 'manifest'
  if (name.endsWith('.sha256')) return 'checksum'
  return 'other'
}

function relativePath(from: string, to: string): string {
  return relative(from, to).replace(/\\/g, '/')
}

function safeTaskName(taskId: DevTaskId): string {
  return taskId.replace(/[^a-z0-9_-]/gi, '-')
}

function logStamp(date = new Date()): string {
  return date.toISOString().replace(/[:.]/g, '-')
}

async function createTaskLog(projectPath: string, taskId: DevTaskId, command: string, startedAt: string): Promise<string> {
  const dir = join(projectPath, '.echo-studio', 'logs')
  await fs.mkdir(dir, { recursive: true })
  const path = join(dir, `${logStamp(new Date(startedAt))}-${safeTaskName(taskId)}.log`)
  await fs.writeFile(path, [
    `ECHO Studio task: ${taskId}`,
    `Command: ${command}`,
    `Started: ${startedAt}`,
    ''
  ].join('\n'), 'utf8')
  return path
}

function resolveTaskLogPath(projectPath: string, logPath: string): string {
  const root = resolve(projectPath, '.echo-studio', 'logs')
  const target = resolve(logPath)
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    throw new Error('Log path must stay inside the project log folder.')
  }
  return target
}

async function appendTaskLog(logPath: string, label: string, text: string): Promise<void> {
  if (!text) return
  await fs.appendFile(logPath, `\n[${label}]\n${text}`, 'utf8')
}

async function finishTaskLog(logPath: string, status: DevTaskRun['status'], finishedAt?: string, exitCode?: number): Promise<void> {
  const lines = ['', `[status] ${status}`]
  if (exitCode !== undefined) lines.push(`[exit] ${exitCode}`)
  if (finishedAt) lines.push(`[finished] ${finishedAt}`)
  lines.push('')
  await fs.appendFile(logPath, lines.join('\n'), 'utf8')
}

function terminateChildProcess(child: ChildProcess): Promise<void> {
  if (!child.pid) {
    child.kill()
    return Promise.resolve()
  }
  if (process.platform === 'win32') {
    return new Promise((resolveTermination) => {
      const killer = spawn('taskkill', ['/PID', String(child.pid), '/T', '/F'], { windowsHide: true })
      let settled = false
      const settle = (): void => {
        if (settled) return
        settled = true
        resolveTermination()
      }
      killer.on('close', settle)
      killer.on('error', () => {
        child.kill()
        settle()
      })
    })
  }
  try {
    process.kill(-child.pid, 'SIGTERM')
  } catch {
    child.kill('SIGTERM')
  }
  return Promise.resolve()
}

async function listArtifactFiles(root: string): Promise<string[]> {
  if (!await exists(root)) return []
  const entries = await fs.readdir(root, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries) {
    const path = join(root, entry.name)
    if (entry.isDirectory()) {
      files.push(...await listArtifactFiles(path))
    } else if (entry.isFile()) {
      files.push(path)
    }
  }
  return files
}

async function collectArtifacts(projectPath: string, echoModulesRoot?: string): Promise<DevArtifact[]> {
  const roots = [
    join(projectPath, 'build', 'libs'),
    join(projectPath, 'release'),
    join(projectPath, 'exports'),
    ...(echoModulesRoot ? [join(echoModulesRoot, 'dist', 'echo-module-release')] : [])
  ]
  const artifacts: DevArtifact[] = []
  for (const root of roots) {
    for (const filePath of await listArtifactFiles(root)) {
      const stat = await fs.stat(filePath)
      artifacts.push({
        path: filePath,
        name: basename(filePath),
        kind: artifactKind(basename(filePath)),
        bytes: stat.size,
        modifiedAt: stat.mtimeMs
      })
    }
  }
  return artifacts.sort((a, b) => b.modifiedAt - a.modifiedAt)
}

async function collectCurrentArtifacts(projectPath: string): Promise<DevArtifact[]> {
  const catalog = await listEchoModules(projectPath).catch(() => undefined)
  return collectArtifacts(projectPath, catalog?.moduleRoot)
}

function runtimeTargets(manifest: AddonManifest, options?: DevWorkspaceOptions): Runtime[] {
  return options?.runtimes?.length ? options.runtimes : manifest.runtime.supports
}

function gradlePropertyValue(value: string | undefined): string {
  return (value ?? '').replace(/\\/g, '/').replace(/\r?\n/g, ' ').trim()
}

function lockModule(mod: EchoModuleRecord): DevModuleLock['modules'][number] {
  return {
    id: mod.id,
    aliases: mod.aliases,
    name: mod.name,
    role: mod.role,
    kind: mod.kind,
    status: mod.status,
    channel: mod.channel,
    publicApi: mod.publicApi,
    ...(mod.trustLevel ? { trustLevel: mod.trustLevel } : {}),
    ...(mod.blocked ? { blocked: mod.blocked } : {}),
    ...(mod.blockReason ? { blockReason: mod.blockReason } : {}),
    requires: mod.requires,
    optional: mod.optional,
    runtimes: mod.runtimes,
    standaloneReady: mod.standaloneReady,
    launcherVisible: mod.launcherVisible,
    ...(mod.version ? { version: mod.version } : {}),
    ...(mod.source ? { source: mod.source } : {}),
    ...(mod.moduleDir ? { moduleDir: mod.moduleDir } : {}),
    ...(mod.descriptorPath ? { descriptorPath: mod.descriptorPath } : {})
  }
}

function buildModuleLock(manifest: AddonManifest, catalogResult: EchoModuleCatalogResult): DevModuleLock {
  const plan = resolveProjectModulePlan(manifest, catalogResult.catalog)
  return {
    schemaVersion: 'echo.studio.modules.lock.v1',
    generatedBy: STUDIO_MARKER,
    generatedAt: new Date().toISOString(),
    project: {
      id: manifest.id,
      version: manifest.version
    },
    catalog: {
      source: catalogResult.source,
      warnings: catalogResult.warnings,
      ...(catalogResult.indexPath ? { indexPath: catalogResult.indexPath } : {}),
      ...(catalogResult.moduleRoot ? { moduleRoot: catalogResult.moduleRoot } : {}),
      ...(catalogResult.generatedAt ? { generatedAt: catalogResult.generatedAt } : {})
    },
    declared: plan.declared,
    normalizedDeclared: plan.normalizedDeclared,
    moduleCount: plan.closure.length,
    modules: plan.closure.map(lockModule),
    missingRequired: plan.missingRequired.map((mod) => mod.id),
    unknown: plan.unknown
  }
}

function moduleCatalogStatus(catalogResult: EchoModuleCatalogResult): DevModuleCatalogStatus {
  return {
    schemaVersion: 'echo.studio.modules.catalog.status.v1',
    source: catalogResult.source,
    localAvailable: catalogResult.source === 'local-index' && Boolean(catalogResult.moduleRoot),
    warnings: catalogResult.warnings,
    ...(catalogResult.indexPath ? { indexPath: catalogResult.indexPath } : {}),
    ...(catalogResult.moduleRoot ? { moduleRoot: catalogResult.moduleRoot } : {}),
    ...(catalogResult.generatedAt ? { generatedAt: catalogResult.generatedAt } : {})
  }
}

function buildModuleWorkspace(manifest: AddonManifest, catalogResult: EchoModuleCatalogResult): DevModuleWorkspaceMap {
  const plan = resolveProjectModulePlan(manifest, catalogResult.catalog)
  const modules = plan.closure.map((mod) => {
    const localSource = Boolean(mod.moduleDir || mod.descriptorPath)
    return {
      id: mod.id,
      name: mod.name,
      role: mod.role,
      publicApi: mod.publicApi,
      ...(mod.trustLevel ? { trustLevel: mod.trustLevel } : {}),
      ...(mod.blocked ? { blocked: mod.blocked } : {}),
      ...(mod.blockReason ? { blockReason: mod.blockReason } : {}),
      runtimes: mod.runtimes,
      requires: mod.requires,
      optional: mod.optional,
      localSource,
      ...(mod.version ? { version: mod.version } : {}),
      ...(mod.source ? { source: mod.source } : {}),
      ...(mod.moduleDir ? { moduleDir: mod.moduleDir } : {}),
      ...(mod.descriptorPath ? { descriptorPath: mod.descriptorPath } : {})
    }
  })

  return {
    schemaVersion: 'echo.studio.modules.workspace.v1',
    generatedBy: STUDIO_MARKER,
    generatedAt: new Date().toISOString(),
    project: {
      id: manifest.id,
      version: manifest.version
    },
    catalog: moduleCatalogStatus(catalogResult),
    declared: plan.declared,
    normalizedDeclared: plan.normalizedDeclared,
    moduleCount: modules.length,
    localModuleCount: modules.filter((mod) => mod.localSource).length,
    modules,
    missingRequired: plan.missingRequired.map((mod) => mod.id),
    unknown: plan.unknown
  }
}

function sortedUnique(values: string[]): string[] {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b))
}

function diffIds(expected: string[], actual: string[]): { missing: string[]; extra: string[] } {
  const expectedSet = new Set(expected)
  const actualSet = new Set(actual)
  return {
    missing: expected.filter((id) => !actualSet.has(id)),
    extra: actual.filter((id) => !expectedSet.has(id))
  }
}

async function moduleLockStatus(
  projectPath: string,
  manifest: AddonManifest,
  plan: ProjectModulePlan,
  mode: DevWorkspaceMode
): Promise<DevModuleLockStatus> {
  const studioLockPath = join(projectPath, '.echo-studio', 'modules.lock.json')
  const runtimeLockPath = join(projectPath, 'src', 'generated', 'resources', 'META-INF', 'echo.modules.lock.json')
  const [studioLock, runtimeLock] = await Promise.all([
    readModuleLock(studioLockPath),
    readModuleLock(runtimeLockPath)
  ])
  const runtimeExpected = mode !== 'visual'
  const expectedModuleIds = sortedUnique(plan.closure.map((mod) => mod.id))
  const lockedModuleIds = sortedUnique(studioLock?.modules.map((mod) => mod.id) ?? [])
  const runtimeModuleIds = sortedUnique(runtimeLock?.modules.map((mod) => mod.id) ?? [])
  const studioDiff = diffIds(expectedModuleIds, lockedModuleIds)
  const runtimeDiff = diffIds(expectedModuleIds, runtimeModuleIds)
  const projectMatches = Boolean(
    studioLock &&
    studioLock.project.id === manifest.id &&
    studioLock.project.version === manifest.version
  )
  const runtimeProjectMatches = !runtimeExpected || Boolean(
    runtimeLock &&
    runtimeLock.project.id === manifest.id &&
    runtimeLock.project.version === manifest.version
  )
  const studioUpToDate = Boolean(studioLock) && projectMatches && studioDiff.missing.length === 0 && studioDiff.extra.length === 0
  const runtimeUpToDate = !runtimeExpected || Boolean(runtimeLock) && runtimeProjectMatches && runtimeDiff.missing.length === 0 && runtimeDiff.extra.length === 0
  return {
    schemaVersion: 'echo.studio.modules.lock.status.v1',
    studioLockPath: relativePath(projectPath, studioLockPath),
    runtimeLockPath: relativePath(projectPath, runtimeLockPath),
    studioExists: Boolean(studioLock),
    runtimeExists: Boolean(runtimeLock),
    runtimeExpected,
    upToDate: studioUpToDate && runtimeUpToDate,
    runtimeUpToDate,
    projectMatches,
    expectedModuleIds,
    lockedModuleIds,
    runtimeModuleIds,
    missingFromLock: studioDiff.missing,
    extraInLock: studioDiff.extra,
    missingFromRuntimeLock: runtimeDiff.missing,
    extraInRuntimeLock: runtimeDiff.extra,
    lockedProjectId: studioLock?.project.id,
    lockedProjectVersion: studioLock?.project.version,
    generatedAt: studioLock?.generatedAt
  }
}

async function moduleWorkspaceStatus(
  projectPath: string,
  manifest: AddonManifest,
  plan: ProjectModulePlan
): Promise<DevModuleWorkspaceStatus> {
  const workspacePath = join(projectPath, '.echo-studio', 'module-workspace.json')
  const workspace = await readModuleWorkspace(workspacePath)
  const expectedModuleIds = sortedUnique(plan.closure.map((mod) => mod.id))
  const mappedModuleIds = sortedUnique(workspace?.modules.map((mod) => mod.id) ?? [])
  const diff = diffIds(expectedModuleIds, mappedModuleIds)
  const projectMatches = Boolean(
    workspace &&
    workspace.project.id === manifest.id &&
    workspace.project.version === manifest.version
  )
  const upToDate = Boolean(workspace) && projectMatches && diff.missing.length === 0 && diff.extra.length === 0

  return {
    schemaVersion: 'echo.studio.modules.workspace.status.v1',
    path: relativePath(projectPath, workspacePath),
    exists: Boolean(workspace),
    upToDate,
    projectMatches,
    moduleCount: workspace?.moduleCount ?? 0,
    localModuleCount: workspace?.localModuleCount ?? 0,
    expectedModuleIds,
    mappedModuleIds,
    missingFromMap: diff.missing,
    extraInMap: diff.extra,
    generatedAt: workspace?.generatedAt
  }
}

function parseGradleProperties(text: string): Record<string, string> {
  const properties: Record<string, string> = {}
  for (const rawLine of text.split(/\r?\n/g)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#') || line.startsWith('!')) continue
    const index = line.search(/[:=]/)
    if (index < 0) continue
    const key = line.slice(0, index).trim()
    const value = line.slice(index + 1).trim()
    if (key) properties[key] = value
  }
  return properties
}

interface ToolchainProbe {
  javaAvailable: boolean
  javaVersion?: string
  javaMajorVersion?: number
  systemGradleAvailable: boolean
  systemGradleVersion?: string
}

let toolchainProbeCache: { at: number; value: ToolchainProbe } | null = null

function parseJavaVersion(output: string): { version?: string; majorVersion?: number } {
  const match = output.match(/(?:openjdk|java)\s+version\s+"?([0-9][^"\s]*)/i) ?? output.match(/\b([0-9]+(?:\.[0-9]+)+)\b/)
  const version = match?.[1]
  if (!version) return {}
  const parts = version.split('.').map((part) => Number.parseInt(part, 10))
  const majorVersion = parts[0] === 1 ? parts[1] : parts[0]
  return Number.isFinite(majorVersion) ? { version, majorVersion } : { version }
}

function parseGradleVersion(output: string): string | undefined {
  return output.match(/\bGradle\s+([0-9][^\s\r\n]*)/i)?.[1]
}

function probeCommand(command: string, args: string[], timeoutMs: number): Promise<{ ok: boolean; output: string }> {
  return new Promise((resolve) => {
    let child: ReturnType<typeof spawn>
    try {
      child = spawn(command, args, { windowsHide: true })
    } catch {
      resolve({ ok: false, output: '' })
      return
    }
    let output = ''
    let settled = false
    function finish(ok: boolean): void {
      if (settled) return
      settled = true
      clearTimeout(timeout)
      resolve({ ok, output })
    }
    const timeout = setTimeout(() => {
      child.kill()
      finish(false)
    }, timeoutMs)
    child.stdout?.on('data', (chunk) => { output += String(chunk) })
    child.stderr?.on('data', (chunk) => { output += String(chunk) })
    child.on('close', (code) => {
      finish(code === 0)
    })
    child.on('error', () => {
      finish(false)
    })
  })
}

async function systemToolchainProbe(): Promise<ToolchainProbe> {
  const now = Date.now()
  if (toolchainProbeCache && now - toolchainProbeCache.at < 30000) return toolchainProbeCache.value

  const gradleExecutable = process.platform === 'win32' ? 'gradle.cmd' : 'gradle'
  const [java, gradle] = await Promise.all([
    probeCommand('java', ['-version'], 2500),
    probeCommand(gradleExecutable, ['--version'], 2500)
  ])
  const javaVersion = java.ok ? parseJavaVersion(java.output) : {}
  const value: ToolchainProbe = {
    javaAvailable: java.ok,
    ...(javaVersion.version ? { javaVersion: javaVersion.version } : {}),
    ...(javaVersion.majorVersion ? { javaMajorVersion: javaVersion.majorVersion } : {}),
    systemGradleAvailable: gradle.ok,
    ...(gradle.ok && parseGradleVersion(gradle.output) ? { systemGradleVersion: parseGradleVersion(gradle.output) } : {})
  }
  toolchainProbeCache = { at: now, value }
  return value
}

async function toolchainStatus(projectPath: string, hasGradleWrapper: boolean): Promise<DevToolchainStatus> {
  const properties = parseGradleProperties(await readText(join(projectPath, 'gradle.properties')))
  const requiredJavaVersion = Number.parseInt(properties.java_language_version ?? '25', 10) || 25
  const probe = await systemToolchainProbe()
  const javaMeetsRequirement = Boolean(probe.javaMajorVersion && probe.javaMajorVersion >= requiredJavaVersion)
  const gradleAvailable = hasGradleWrapper || probe.systemGradleAvailable
  const issues = [
    !probe.javaAvailable ? 'Java is not available on PATH.' : '',
    probe.javaAvailable && !javaMeetsRequirement
      ? `Java ${probe.javaVersion ?? 'version'} is below the generated target ${requiredJavaVersion}.`
      : '',
    !gradleAvailable ? 'No generated Gradle launcher or system Gradle was found.' : ''
  ].filter(Boolean)

  return {
    schemaVersion: 'echo.studio.toolchain.status.v1',
    requiredJavaVersion,
    ...(process.env.JAVA_HOME ? { javaHome: process.env.JAVA_HOME } : {}),
    javaAvailable: probe.javaAvailable,
    ...(probe.javaVersion ? { javaVersion: probe.javaVersion } : {}),
    ...(probe.javaMajorVersion ? { javaMajorVersion: probe.javaMajorVersion } : {}),
    javaMeetsRequirement,
    gradleWrapper: hasGradleWrapper,
    gradleAvailable,
    ...(probe.systemGradleVersion ? { gradleVersion: probe.systemGradleVersion } : {}),
    gradleCommand: hasGradleWrapper ? (process.platform === 'win32' ? '.\\gradlew.bat' : './gradlew') : 'gradle',
    issues
  }
}

async function runtimeLauncherStatus(
  projectPath: string,
  runtimes: Runtime[],
  mode: DevWorkspaceMode
): Promise<DevRuntimeLauncherStatus> {
  const gradlePropertiesPath = join(projectPath, 'gradle.properties')
  const gradlePropertiesExists = await exists(gradlePropertiesPath)
  const properties = parseGradleProperties(await readText(gradlePropertiesPath))
  const nativeExecutable = properties.echo_native_executable ?? ''
  const standaloneExecutable = properties.echo_standalone_executable ?? ''
  const nativeExpected = mode !== 'visual' && runtimes.includes('echo_native')
  const standaloneExpected = mode !== 'visual' && runtimes.includes('standalone')
  const nativeConfigured = nativeExecutable.trim().length > 0
  const standaloneConfigured = standaloneExecutable.trim().length > 0

  return {
    schemaVersion: 'echo.studio.runtime.launchers.status.v1',
    gradlePropertiesPath: relativePath(projectPath, gradlePropertiesPath),
    gradlePropertiesExists,
    nativeExpected,
    nativeConfigured,
    nativeExecutable,
    standaloneExpected,
    standaloneConfigured,
    standaloneExecutable,
    ready: (!nativeExpected || nativeConfigured) && (!standaloneExpected || standaloneConfigured)
  }
}

function gradleProperties(manifest: AddonManifest, runtimes: Runtime[], options?: DevWorkspaceOptions): string {
  return `# ${STUDIO_MARKER}
mod_id=${localId(manifest)}
mod_name=${manifest.name}
mod_version=${manifest.version}
mod_group_id=dev.echo.${manifest.namespace}
mod_license=All Rights Reserved
java_language_version=25
echo_gradle_version=${GRADLE_VERSION}
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.200
enable_neoforge=${String(runtimes.includes('neoforge'))}
enable_echo_native=${String(runtimes.includes('echo_native'))}
enable_standalone=${String(runtimes.includes('standalone'))}
echo_native_executable=${gradlePropertyValue(options?.runtimeTools?.echoNativeExecutable)}
echo_standalone_executable=${gradlePropertyValue(options?.runtimeTools?.standaloneExecutable)}
`
}

function settingsGradle(manifest: AddonManifest): string {
  return `// ${STUDIO_MARKER}
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

rootProject.name = "${localId(manifest)}"
`
}

function buildGradle(): string {
  return `// ${STUDIO_MARKER}
plugins {
    id "java-library"
    id "maven-publish"
    id "net.neoforged.moddev" version "2.0.141" apply false
    id "idea"
}

def enableNeoForge = providers.gradleProperty("enable_neoforge").orElse("false").get().toBoolean()
def enableNative = providers.gradleProperty("enable_echo_native").orElse("false").get().toBoolean()
def enableStandalone = providers.gradleProperty("enable_standalone").orElse("false").get().toBoolean()
def echoNativeExecutable = providers.gradleProperty("echo_native_executable").orElse("")
def echoStandaloneExecutable = providers.gradleProperty("echo_standalone_executable").orElse("")
def echoModuleWorkspaceFile = file(".echo-studio/module-workspace.json")

version = providers.gradleProperty("mod_version").get()
group = providers.gradleProperty("mod_group_id").get()

base {
    archivesName = providers.gradleProperty("mod_id").get()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(providers.gradleProperty("java_language_version").orElse("25").get().toInteger())
    }
}

repositories {
    mavenCentral()
    maven { url = uri("https://maven.neoforged.net/releases") }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:5.10.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
}

sourceSets.main.resources {
    srcDir("src/generated/resources")
}

tasks.register("echoModuleWorkspace") {
    group = "echo dev"
    description = "Prints the resolved ECHO module closure and linked local source folders."
    doLast {
        if (!echoModuleWorkspaceFile.exists()) {
            throw new GradleException("ECHO module workspace map is missing. Run Set Up Workspace in ECHO Studio.")
        }
        def map = new groovy.json.JsonSlurper().parse(echoModuleWorkspaceFile)
        println "ECHO module workspace: \${map.moduleCount ?: 0} module(s), \${map.localModuleCount ?: 0} local source link(s)."
        (map.modules ?: []).each { module ->
            def source = module.localSource ? (module.moduleDir ?: module.descriptorPath ?: "local source") : "catalog metadata"
            println " - \${module.id} (\${module.publicApi ?: 'api unknown'}) -> \${source}"
        }
    }
}

if (enableNeoForge) {
    apply plugin: "net.neoforged.moddev"

    neoForge {
        version = providers.gradleProperty("neo_version").get()
        runs {
            client {
                client()
                systemProperty "neoforge.enabledGameTestNamespaces", providers.gradleProperty("mod_id").get()
            }
            server {
                server()
                programArgument "--nogui"
                systemProperty "neoforge.enabledGameTestNamespaces", providers.gradleProperty("mod_id").get()
            }
            data {
                clientData()
                programArguments.addAll "--mod", providers.gradleProperty("mod_id").get(), "--all",
                    "--output", file("src/generated/resources/").absolutePath,
                    "--existing", file("src/main/resources/").absolutePath
            }
            configureEach {
                systemProperty "forge.logging.markers", "REGISTRIES"
            }
        }
        mods {
            "\${providers.gradleProperty("mod_id").get()}" {
                sourceSet(sourceSets.main)
            }
        }
    }
} else {
    tasks.register("runClient") {
        group = "echo dev"
        description = "Placeholder NeoForge client task. Enable NeoForge in gradle.properties to wire the real client."
        doLast { println "NeoForge is not enabled for this workspace." }
    }
    tasks.register("runServer") {
        group = "echo dev"
        description = "Placeholder server task. Enable NeoForge in gradle.properties to wire the real server."
        doLast { println "NeoForge is not enabled for this workspace." }
    }
    tasks.register("runData") {
        group = "echo dev"
        description = "Placeholder data generation task."
        doLast { println "Data generation is not configured for this workspace." }
    }
}

tasks.register("echoNativePreview", Exec) {
    group = "echo dev"
    description = "Starts the native preview lane when the ECHO Native runtime is installed."
    doFirst {
        if (!enableNative) throw new GradleException("ECHO Native is not enabled for this workspace.")
        def executablePath = echoNativeExecutable.get().trim()
        if (!executablePath) throw new GradleException("Set echo_native_executable in gradle.properties or ECHO Studio Settings before starting native preview.")
        executable = executablePath
        args "--project", projectDir.absolutePath,
            "--manifest", file("echo.mod.json").absolutePath,
            "--modules-lock", file("src/generated/resources/META-INF/echo.modules.lock.json").absolutePath
    }
}

tasks.register("echoStandalonePreview", Exec) {
    group = "echo dev"
    description = "Starts the standalone runtime preview lane when the ECHO Standalone runtime is installed."
    doFirst {
        if (!enableStandalone) throw new GradleException("Standalone runtime is not enabled for this workspace.")
        def executablePath = echoStandaloneExecutable.get().trim()
        if (!executablePath) throw new GradleException("Set echo_standalone_executable in gradle.properties or ECHO Studio Settings before starting standalone preview.")
        executable = executablePath
        args "--project", projectDir.absolutePath,
            "--manifest", file("echo.mod.json").absolutePath,
            "--modules-lock", file("src/generated/resources/META-INF/echo.modules.lock.json").absolutePath
    }
}

tasks.register("studioPackage") {
    group = "echo release"
    description = "Studio packaging is run from the ECHO Studio Release page."
    dependsOn("build")
    doLast { println "Use ECHO Studio Release to generate .echo-addon, checksums, and echo-release.json." }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.named("test") {
    useJUnitPlatform()
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
`
}

function javaSource(manifest: AddonManifest): string {
  const pkg = packagePath(manifest).replace(/\//g, '.')
  return `// ${STUDIO_MARKER}
package ${pkg};

/**
 * Local development entrypoint scaffold for ${manifest.name}.
 *
 * Replace this class with your real runtime hooks as the project grows.
 */
public final class ${className(manifest)} {
    public static final String ID = "${manifest.id}";

    private ${className(manifest)}() {
    }

    public static void initialize() {
        System.out.println("Initializing ECHO project: " + ID);
    }
}
`
}

function testSource(manifest: AddonManifest): string {
  const pkg = packagePath(manifest).replace(/\//g, '.')
  return `// ${STUDIO_MARKER}
package ${pkg};

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

final class ${className(manifest)}Test {
    @Test
    void exposesProjectId() {
        assertEquals("${manifest.id}", ${className(manifest)}.ID);
    }
}
`
}

function gradlewBat(): string {
  return `@echo off
REM ${STUDIO_MARKER}
setlocal
set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%" >nul
set "GRADLE_VERSION=${GRADLE_VERSION}"
set "GRADLE_DIST_URL=${GRADLE_DISTRIBUTION_URL}"
set "GRADLE_CACHE=%SCRIPT_DIR%.gradle\\studio"
set "GRADLE_HOME=%GRADLE_CACHE%\\gradle-%GRADLE_VERSION%"
set "GRADLE_BIN=%GRADLE_HOME%\\bin\\gradle.bat"

if not exist "%GRADLE_BIN%" (
  echo ECHO Studio: preparing Gradle %GRADLE_VERSION%...
  powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $url=$env:GRADLE_DIST_URL; $cache=$env:GRADLE_CACHE; $zip=Join-Path $cache ('gradle-' + $env:GRADLE_VERSION + '-bin.zip'); New-Item -ItemType Directory -Force $cache | Out-Null; if (!(Test-Path $zip)) { Invoke-WebRequest -Uri $url -OutFile $zip }; Expand-Archive -Path $zip -DestinationPath $cache -Force"
  if errorlevel 1 (
    popd >nul
    exit /b 1
  )
)
"%GRADLE_BIN%" %*
set "EXIT_CODE=%errorlevel%"
popd >nul
exit /b %EXIT_CODE%
`
}

function gradlewSh(): string {
  return `#!/usr/bin/env sh
# ${STUDIO_MARKER}
set -eu

APP_HOME=$(CDPATH= cd "$(dirname "$0")" && pwd)
cd "$APP_HOME"

GRADLE_VERSION="${GRADLE_VERSION}"
GRADLE_DIST_URL="${GRADLE_DISTRIBUTION_URL}"
GRADLE_CACHE="$APP_HOME/.gradle/studio"
GRADLE_HOME="$GRADLE_CACHE/gradle-$GRADLE_VERSION"
GRADLE_BIN="$GRADLE_HOME/bin/gradle"
GRADLE_ZIP="$GRADLE_CACHE/gradle-$GRADLE_VERSION-bin.zip"

if [ ! -x "$GRADLE_BIN" ]; then
  echo "ECHO Studio: preparing Gradle $GRADLE_VERSION..."
  mkdir -p "$GRADLE_CACHE"
  if [ ! -f "$GRADLE_ZIP" ]; then
    if command -v curl >/dev/null 2>&1; then
      curl -L "$GRADLE_DIST_URL" -o "$GRADLE_ZIP"
    elif command -v wget >/dev/null 2>&1; then
      wget -O "$GRADLE_ZIP" "$GRADLE_DIST_URL"
    else
      echo "curl or wget is required to download Gradle." >&2
      exit 1
    fi
  fi
  if ! command -v unzip >/dev/null 2>&1; then
    echo "unzip is required to expand Gradle." >&2
    exit 1
  fi
  unzip -oq "$GRADLE_ZIP" -d "$GRADLE_CACHE"
  chmod +x "$GRADLE_BIN" || true
fi

exec "$GRADLE_BIN" "$@"
`
}

function runScript(task: 'run-dev-client' | 'build-local', manifest: AddonManifest): string {
  const command = task === 'run-dev-client' ? './gradlew.bat runClient' : './gradlew.bat build'
  return `# ${STUDIO_MARKER}
Set-Location -LiteralPath $PSScriptRoot\\..
Write-Host "ECHO Studio: ${task === 'run-dev-client' ? 'starting dev client' : 'building local artifacts'} for ${manifest.id}"
${command}
`
}

function releaseChecklist(manifest: AddonManifest): string {
  return `# ${STUDIO_MARKER}
# Local Release Checklist

Project: ${manifest.name}
ID: ${manifest.id}
Version: ${manifest.version}

1. Run Gradle tests from ECHO Studio.
2. Run Package Local Release from ECHO Studio.
3. Review exports/echo-release.json, exports/checksums.sha256, and exports/release-index-submission.md.
4. Create the GitHub draft from Publish Assistant when the local package is ready.
5. Submit release-index-handoff.json with release-index-submission.md for Release Index ingestion review.
`
}

function expectedModes(rel: string): DevWorkspaceMode[] {
  if (
    rel === 'echo.mod.json' ||
    rel === '.echo-studio/dev-workspace.json' ||
    rel === '.echo-studio/modules.lock.json' ||
    rel === '.echo-studio/module-workspace.json'
  ) return ['visual', 'gradle', 'full']
  if (
    [
      'settings.gradle',
      'build.gradle',
      'gradle.properties',
      'gradlew.bat',
      'gradlew',
      'src/main/resources/META-INF/echo.mod.json',
      'src/generated/resources/META-INF/echo.modules.lock.json'
    ].includes(rel) ||
    rel.startsWith('src/main/java/') ||
    rel.startsWith('src/test/java/') ||
    rel.startsWith('scripts/')
  ) {
    return ['gradle', 'full']
  }
  if (rel === 'META-INF/echo-addon-package.json' || rel === 'release' || rel === '.echo-studio/release-checklist.md') {
    return ['full']
  }
  return []
}

function isExpectedForMode(rel: string, mode: DevWorkspaceMode, runtimes: Runtime[]): boolean {
  if (rel === 'src/generated/resources/META-INF/neoforge.mods.toml') {
    return mode !== 'visual' && runtimes.includes('neoforge')
  }
  return expectedModes(rel).includes(mode)
}

async function fileStatus(projectPath: string, rel: string, mode: DevWorkspaceMode, runtimes: Runtime[]): Promise<DevWorkspaceFileStatus> {
  const path = join(projectPath, rel)
  const isThere = await exists(path)
  return {
    path: rel,
    exists: isThere,
    generatedByStudio: isThere ? (await readText(path)).includes(STUDIO_MARKER) : false,
    expected: isExpectedForMode(rel, mode, runtimes)
  }
}

export async function inspectDevWorkspace(projectPath: string): Promise<DevWorkspaceState> {
  const manifest = await readManifest(projectPath)
  if (!manifest) throw new Error('Missing echo.mod.json')
  const moduleCatalog = await listEchoModules(projectPath)
  const studioStatePath = join(projectPath, '.echo-studio', 'dev-workspace.json')
  const saved = await readText(studioStatePath)
  const parsed = saved ? JSON.parse(saved) as Partial<DevWorkspaceState> : {}
  const mode = parsed.mode ?? 'visual'
  const runtimes = parsed.runtimeTargets ?? manifest.runtime.supports
  const javaPath = `src/main/java/${packagePath(manifest)}/${className(manifest)}.java`
  const testPath = `src/test/java/${packagePath(manifest)}/${className(manifest)}Test.java`
  const files = await Promise.all([
    fileStatus(projectPath, 'echo.mod.json', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/dev-workspace.json', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/modules.lock.json', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/module-workspace.json', mode, runtimes),
    fileStatus(projectPath, 'META-INF/echo-addon-package.json', mode, runtimes),
    fileStatus(projectPath, 'settings.gradle', mode, runtimes),
    fileStatus(projectPath, 'build.gradle', mode, runtimes),
    fileStatus(projectPath, 'gradle.properties', mode, runtimes),
    fileStatus(projectPath, 'gradlew.bat', mode, runtimes),
    fileStatus(projectPath, 'gradlew', mode, runtimes),
    fileStatus(projectPath, 'src/main/resources/META-INF/echo.mod.json', mode, runtimes),
    fileStatus(projectPath, 'src/generated/resources/META-INF/echo.modules.lock.json', mode, runtimes),
    fileStatus(projectPath, 'src/generated/resources/META-INF/neoforge.mods.toml', mode, runtimes),
    fileStatus(projectPath, javaPath, mode, runtimes),
    fileStatus(projectPath, testPath, mode, runtimes),
    fileStatus(projectPath, 'scripts/run-dev-client.ps1', mode, runtimes),
    fileStatus(projectPath, 'scripts/build-local.ps1', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/release-checklist.md', mode, runtimes),
    fileStatus(projectPath, 'release', mode, runtimes)
  ])
  const modulePlan = resolveProjectModulePlan(manifest, moduleCatalog.catalog)
  const hasGradleWrapper = files.some((file) => ['gradlew.bat', 'gradlew'].includes(file.path) && file.exists)
  const gradleReady = files.some((file) => file.path === 'build.gradle' && file.exists) && files.some((file) => file.path === 'settings.gradle' && file.exists)
  const sourceReady = files.some((file) => file.path.startsWith('src/main/java') && file.exists)
  const expectedReady = files.filter((file) => file.expected).every((file) => file.exists)
  const lockStatus = await moduleLockStatus(projectPath, manifest, modulePlan, mode)
  const moduleWorkspace = await moduleWorkspaceStatus(projectPath, manifest, modulePlan)
  const runtimeLaunchers = await runtimeLauncherStatus(projectPath, runtimes, mode)
  const toolchain = await toolchainStatus(projectPath, hasGradleWrapper)
  return {
    ready: Boolean(parsed.lastSetupAt) && expectedReady && lockStatus.upToDate && moduleWorkspace.upToDate,
    mode,
    projectPath,
    gradleReady,
    hasGradleWrapper,
    sourceReady,
    runtimeTargets: runtimes,
    files,
    toolchain,
    modulePlan,
    moduleCatalog: moduleCatalogStatus(moduleCatalog),
    moduleWorkspace,
    moduleLock: lockStatus,
    runtimeLaunchers,
    artifacts: await collectArtifacts(projectPath, moduleCatalog.moduleRoot),
    lastSetupAt: parsed.lastSetupAt
  }
}

export async function setupDevWorkspace(projectPath: string, options: DevWorkspaceOptions): Promise<DevSetupResult> {
  const manifest = await readManifest(projectPath)
  if (!manifest) throw new Error('Missing echo.mod.json')
  const runtimes = runtimeTargets(manifest, options)
  const moduleCatalog = await listEchoModules(projectPath)
  const moduleLock = buildModuleLock(manifest, moduleCatalog)
  const moduleLockJson = `${JSON.stringify(moduleLock, null, 2)}\n`
  const moduleWorkspace = buildModuleWorkspace(manifest, moduleCatalog)
  const moduleWorkspaceJson = `${JSON.stringify(moduleWorkspace, null, 2)}\n`
  const written: string[] = []
  const skipped: string[] = []
  const force = Boolean(options.force)

  await fs.mkdir(join(projectPath, '.echo-studio'), { recursive: true })
  await writeGenerated(join(projectPath, '.echo-studio', 'modules.lock.json'), moduleLockJson, written)
  await writeGenerated(join(projectPath, '.echo-studio', 'module-workspace.json'), moduleWorkspaceJson, written)

  if (options.mode === 'gradle' || options.mode === 'full') {
    await writeIfAllowed(join(projectPath, 'settings.gradle'), settingsGradle(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'gradle.properties'), gradleProperties(manifest, runtimes, options), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'build.gradle'), buildGradle(), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'gradlew.bat'), gradlewBat(), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'gradlew'), gradlewSh(), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'src', 'main', 'resources', 'META-INF', 'echo.mod.json'), JSON.stringify(manifest, null, 2), force, written, skipped)
    await writeGenerated(join(projectPath, 'src', 'generated', 'resources', 'META-INF', 'echo.modules.lock.json'), moduleLockJson, written)
    if (runtimes.includes('neoforge')) {
      await writeGenerated(join(projectPath, 'src', 'generated', 'resources', 'META-INF', 'neoforge.mods.toml'), buildNeoForgeModsToml(manifest), written)
    }
    await writeIfAllowed(join(projectPath, 'src', 'main', 'java', ...packagePath(manifest).split('/'), `${className(manifest)}.java`), javaSource(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'src', 'test', 'java', ...packagePath(manifest).split('/'), `${className(manifest)}Test.java`), testSource(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'scripts', 'run-dev-client.ps1'), runScript('run-dev-client', manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'scripts', 'build-local.ps1'), runScript('build-local', manifest), force, written, skipped)
  }

  if (options.mode === 'full') {
    await writeIfAllowed(
      join(projectPath, 'META-INF', 'echo-addon-package.json'),
      JSON.stringify(buildAddonPackageManifest(manifest, moduleCatalog.catalog), null, 2),
      force,
      written,
      skipped
    )
    const releaseDir = join(projectPath, 'release')
    const releaseExists = await exists(releaseDir)
    await fs.mkdir(releaseDir, { recursive: true })
    if (releaseExists && !force) skipped.push(releaseDir)
    else written.push(releaseDir)
    await writeIfAllowed(join(projectPath, '.echo-studio', 'release-checklist.md'), releaseChecklist(manifest), force, written, skipped)
  }

  const statePath = join(projectPath, '.echo-studio', 'dev-workspace.json')
  await fs.writeFile(statePath, JSON.stringify({
    mode: options.mode,
    runtimeTargets: runtimes,
    lastSetupAt: new Date().toISOString()
  }, null, 2), 'utf8')
  written.push(statePath)

  return {
    state: await inspectDevWorkspace(projectPath),
    written: written.map((path) => relative(projectPath, path)),
    skipped: skipped.map((path) => relative(projectPath, path))
  }
}

function gradleCommand(projectPath: string): string {
  if (process.platform === 'win32' && existsSync(join(projectPath, 'gradlew.bat'))) return '.\\gradlew.bat'
  if (existsSync(join(projectPath, 'gradlew'))) return './gradlew'
  return 'gradle'
}

function runShell(command: string, cwd: string, timeoutMs: number): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(command, {
      cwd,
      shell: true,
      windowsHide: true
    })
    let stdout = ''
    let stderr = ''
    const timeout = setTimeout(() => {
      child.kill()
      stderr += `\nCommand timed out after ${timeoutMs}ms.`
    }, timeoutMs)
    child.stdout?.on('data', (chunk) => { stdout += String(chunk) })
    child.stderr?.on('data', (chunk) => { stderr += String(chunk) })
    child.on('close', (code) => {
      clearTimeout(timeout)
      resolve({ exitCode: code ?? 0, stdout, stderr })
    })
    child.on('error', (error) => {
      clearTimeout(timeout)
      resolve({ exitCode: 1, stdout, stderr: `${stderr}\n${error.message}` })
    })
  })
}

function isEchoModulesTask(taskId: DevTaskId): boolean {
  return taskId.startsWith('modules:')
}

function selectedLocalModuleIds(plan: ProjectModulePlan): string[] {
  return sortedUnique(
    plan.closure
      .filter((mod) => mod.moduleDir || mod.descriptorPath)
      .map((mod) => mod.id)
  )
}

function assertSafeModuleTaskId(moduleId: string): string {
  if (!/^[A-Za-z0-9._-]+$/.test(moduleId)) throw new Error(`Unsafe ECHO module id for task command: ${moduleId}`)
  return moduleId
}

async function echoModulesTaskCommand(projectPath: string, taskId: DevTaskId): Promise<{ command: string; cwd: string }> {
  const catalog = await listEchoModules(projectPath)
  if (!catalog.moduleRoot) throw new Error('Local ECHO-Modules metadata/modules/index.json was not found.')

  const script = (name: string): string => join(catalog.moduleRoot!, 'scripts', name)
  const requireScript = async (name: string): Promise<void> => {
    if (!await exists(script(name))) throw new Error(`Local ECHO-Modules scripts/${name} was not found.`)
  }

  if (taskId === 'modules:validate') {
    await requireScript('validate-module-graph.mjs')
    return { command: 'node scripts/validate-module-graph.mjs', cwd: catalog.moduleRoot }
  }
  if (taskId === 'modules:docsAudit') {
    await requireScript('docs-audit.mjs')
    return { command: 'node scripts/docs-audit.mjs', cwd: catalog.moduleRoot }
  }
  if (taskId === 'modules:verifyRelease') {
    await requireScript('verify-module-release.mjs')
    return { command: 'node scripts/verify-module-release.mjs --release-dir dist/echo-module-release', cwd: catalog.moduleRoot }
  }

  if (taskId === 'modules:releaseSelected' || taskId === 'modules:releaseAll') {
    await requireScript('generate-module-release.mjs')
    const args = ['node scripts/generate-module-release.mjs --out dist/echo-module-release --package-from-source']
    if (taskId === 'modules:releaseSelected') {
      const manifest = await readManifest(projectPath)
      if (!manifest) throw new Error('Missing echo.mod.json')
      const selected = selectedLocalModuleIds(resolveProjectModulePlan(manifest, catalog.catalog))
      if (selected.length === 0) {
        throw new Error('No resolved modules are linked to local ECHO-Modules source.')
      }
      for (const moduleId of selected) args.push(`--module ${assertSafeModuleTaskId(moduleId)}`)
    }
    return { command: args.join(' '), cwd: catalog.moduleRoot }
  }

  throw new Error(`Unsupported ECHO-Modules task: ${taskId}`)
}

export async function runDevTask(projectPath: string, taskId: DevTaskId): Promise<DevTaskRun> {
  const task = DEV_TASKS.find((item) => item.id === taskId)
  if (!task) throw new Error(`Unknown dev task: ${taskId}`)
  const startedAt = new Date().toISOString()
  await assertDevTaskReady(projectPath, task)

  if (isEchoModulesTask(task.id)) {
    const { command, cwd } = await echoModulesTaskCommand(projectPath, task.id)
    const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
    const result = await runShell(command, cwd, 180000)
    const status = result.exitCode === 0 ? 'completed' : 'failed'
    const finishedAt = new Date().toISOString()
    await appendTaskLog(logPath, 'stdout', result.stdout)
    await appendTaskLog(logPath, 'stderr', result.stderr)
    await finishTaskLog(logPath, status, finishedAt, result.exitCode)
    return {
      taskId,
      status,
      command,
      cwd,
      logPath,
      exitCode: result.exitCode,
      stdout: result.stdout,
      stderr: result.stderr,
      startedAt,
      finishedAt,
      artifacts: await collectArtifacts(projectPath, cwd)
    }
  }

  if (task.id === 'package:local') {
    const command = 'ECHO Studio packageAddon'
    const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
    let result: Awaited<ReturnType<typeof packageAddon>>
    try {
      result = await packageAddon(projectPath, await inspectDevWorkspace(projectPath))
    } catch (error) {
      const finishedAt = new Date().toISOString()
      await appendTaskLog(logPath, 'error', error instanceof Error ? error.message : String(error))
      await finishTaskLog(logPath, 'failed', finishedAt)
      throw error
    }
    const stdout = `Prepared ${basename(result.zipPath)} with ${result.assetPaths.length} release asset(s).`
    const stderr = result.sdkValidation.issues.join('\n')
    const finishedAt = new Date().toISOString()
    await appendTaskLog(logPath, 'stdout', stdout)
    await appendTaskLog(logPath, 'stderr', stderr)
    await finishTaskLog(logPath, 'completed', finishedAt, 0)
    return {
      taskId,
      status: 'completed',
      command,
      cwd: projectPath,
      logPath,
      stdout,
      stderr,
      startedAt,
      finishedAt,
      artifacts: await collectCurrentArtifacts(projectPath)
    }
  }

  const command = `${gradleCommand(projectPath)} ${task.command}`
  const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
  if (task.detached) {
    const taskLogPath = resolveTaskLogPath(projectPath, logPath)
    const child = spawn(command, {
      cwd: projectPath,
      shell: true,
      detached: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true
    })
    const running: RunningDevProcess = {
      child,
      taskId,
      command,
      cwd: projectPath,
      logPath: taskLogPath,
      startedAt,
      stopping: false
    }
    runningDevProcesses.set(taskLogPath, running)
    child.stdout?.on('data', (chunk) => { void appendTaskLog(logPath, 'stdout', String(chunk)) })
    child.stderr?.on('data', (chunk) => { void appendTaskLog(logPath, 'stderr', String(chunk)) })
    child.on('close', (code) => {
      const current = runningDevProcesses.get(taskLogPath)
      if (current === running) runningDevProcesses.delete(taskLogPath)
      if (!running.stopping) {
        void finishTaskLog(logPath, code === 0 ? 'completed' : 'failed', new Date().toISOString(), code ?? undefined)
      }
    })
    child.on('error', (error) => {
      const current = runningDevProcesses.get(taskLogPath)
      if (current === running) runningDevProcesses.delete(taskLogPath)
      void appendTaskLog(logPath, 'error', error.message)
      if (!running.stopping) void finishTaskLog(logPath, 'failed', new Date().toISOString())
    })
    child.unref()
    return {
      taskId,
      status: 'started',
      command,
      cwd: projectPath,
      pid: child.pid,
      logPath,
      stdout: `Started ${task.label} as process ${child.pid}.`,
      stderr: '',
      startedAt,
      artifacts: await collectCurrentArtifacts(projectPath)
    }
  }

  const result = await runShell(command, projectPath, 180000)
  const status = result.exitCode === 0 ? 'completed' : 'failed'
  const finishedAt = new Date().toISOString()
  await appendTaskLog(logPath, 'stdout', result.stdout)
  await appendTaskLog(logPath, 'stderr', result.stderr)
  await finishTaskLog(logPath, status, finishedAt, result.exitCode)
  return {
    taskId,
    status,
    command,
    cwd: projectPath,
    logPath,
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    startedAt,
    finishedAt,
    artifacts: await collectCurrentArtifacts(projectPath)
  }
}

export async function listRunningDevTasks(projectPath: string): Promise<DevTaskRun[]> {
  const projectRoot = resolve(projectPath)
  const artifacts = await collectCurrentArtifacts(projectPath)
  return [...runningDevProcesses.values()]
    .filter((running) => resolve(running.cwd) === projectRoot)
    .sort((a, b) => b.startedAt.localeCompare(a.startedAt))
    .map((running) => ({
      taskId: running.taskId,
      status: 'started',
      command: running.command,
      cwd: running.cwd,
      ...(running.child.pid ? { pid: running.child.pid } : {}),
      logPath: running.logPath,
      stdout: `Started ${running.taskId} as process ${running.child.pid}.`,
      stderr: '',
      startedAt: running.startedAt,
      artifacts
    }))
}

export async function stopDevTask(projectPath: string, logPath: string): Promise<DevTaskStopResult> {
  const taskLogPath = resolveTaskLogPath(projectPath, logPath)
  const running = runningDevProcesses.get(taskLogPath)
  if (!running) {
    return {
      status: 'not_running',
      logPath: taskLogPath,
      message: 'No running dev task was found for this log.'
    }
  }
  running.stopping = true
  runningDevProcesses.delete(taskLogPath)
  const finishedAt = new Date().toISOString()
  await appendTaskLog(taskLogPath, 'stop', 'Stop requested from ECHO Studio.')
  await terminateChildProcess(running.child)
  await finishTaskLog(taskLogPath, 'stopped', finishedAt)
  return {
    status: 'stopped',
    taskId: running.taskId,
    command: running.command,
    cwd: running.cwd,
    ...(running.child.pid ? { pid: running.child.pid } : {}),
    logPath: taskLogPath,
    finishedAt,
    message: `Stopped ${running.taskId}.`
  }
}

export async function readDevTaskLog(projectPath: string, logPath: string): Promise<string> {
  const target = resolveTaskLogPath(projectPath, logPath)
  const text = await fs.readFile(target, 'utf8')
  return text.length > 200000 ? text.slice(-200000) : text
}
