import { existsSync, promises as fs } from 'fs'
import { basename, dirname, join, relative, resolve, sep } from 'path'
import { spawn } from 'child_process'
import { buildAddonPackageManifest } from '../shared/templates'
import { DEV_TASKS, type DevArtifact, type DevSetupResult, type DevTaskId, type DevTaskRun, type DevWorkspaceOptions, type DevWorkspaceState } from '../shared/devWorkspace'
import { resolveProjectModulePlan } from '../shared/moduleCatalog'
import type { AddonManifest, Runtime } from '../shared/types'
import { packageAddon } from './packageService'
import { readManifest } from './fsService'
import { listEchoModules } from './moduleCatalogService'

const STUDIO_MARKER = 'Generated by ECHO Studio'

async function exists(path: string): Promise<boolean> {
  try {
    await fs.access(path)
    return true
  } catch {
    return false
  }
}

async function readText(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf8')
  } catch {
    return ''
  }
}

async function writeIfAllowed(path: string, content: string, force: boolean, written: string[], skipped: string[]): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true })
  if (!force && await exists(path)) {
    skipped.push(path)
    return
  }
  await fs.writeFile(path, content, 'utf8')
  written.push(path)
}

function localId(manifest: AddonManifest): string {
  return manifest.id.includes(':') ? manifest.id.split(':')[1] : manifest.id
}

function className(manifest: AddonManifest): string {
  return localId(manifest)
    .split(/[_-]/g)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join('') + 'Module'
}

function packagePath(manifest: AddonManifest): string {
  return `studio/generated/${manifest.namespace.replace(/[^a-z0-9_]/gi, '').toLowerCase()}/${localId(manifest).replace(/[^a-z0-9_]/gi, '').toLowerCase()}`.replace(/\//g, '/')
}

function artifactKind(name: string): DevArtifact['kind'] {
  if (name.endsWith('.echo-addon')) return 'echo-addon'
  if (name.endsWith('.jar')) return 'jar'
  if (name.endsWith('.json')) return 'manifest'
  if (name.endsWith('.sha256')) return 'checksum'
  return 'other'
}

function safeTaskName(taskId: DevTaskId): string {
  return taskId.replace(/[^a-z0-9_-]/gi, '-')
}

function logStamp(date = new Date()): string {
  return date.toISOString().replace(/[:.]/g, '-')
}

async function createTaskLog(projectPath: string, taskId: DevTaskId, command: string, startedAt: string): Promise<string> {
  const dir = join(projectPath, '.echo-studio', 'logs')
  await fs.mkdir(dir, { recursive: true })
  const path = join(dir, `${logStamp(new Date(startedAt))}-${safeTaskName(taskId)}.log`)
  await fs.writeFile(path, [
    `ECHO Studio task: ${taskId}`,
    `Command: ${command}`,
    `Started: ${startedAt}`,
    ''
  ].join('\n'), 'utf8')
  return path
}

async function appendTaskLog(logPath: string, label: string, text: string): Promise<void> {
  if (!text) return
  await fs.appendFile(logPath, `\n[${label}]\n${text}`, 'utf8')
}

async function finishTaskLog(logPath: string, status: DevTaskRun['status'], finishedAt?: string, exitCode?: number): Promise<void> {
  const lines = ['', `[status] ${status}`]
  if (exitCode !== undefined) lines.push(`[exit] ${exitCode}`)
  if (finishedAt) lines.push(`[finished] ${finishedAt}`)
  lines.push('')
  await fs.appendFile(logPath, lines.join('\n'), 'utf8')
}

async function collectArtifacts(projectPath: string): Promise<DevArtifact[]> {
  const roots = [join(projectPath, 'build', 'libs'), join(projectPath, 'release')]
  const artifacts: DevArtifact[] = []
  for (const root of roots) {
    if (!await exists(root)) continue
    const entries = await fs.readdir(root, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isFile()) continue
      const path = join(root, entry.name)
      const stat = await fs.stat(path)
      artifacts.push({
        path,
        name: entry.name,
        kind: artifactKind(entry.name),
        bytes: stat.size,
        modifiedAt: stat.mtimeMs
      })
    }
  }
  return artifacts.sort((a, b) => b.modifiedAt - a.modifiedAt)
}

function runtimeTargets(manifest: AddonManifest, options?: DevWorkspaceOptions): Runtime[] {
  return options?.runtimes?.length ? options.runtimes : manifest.runtime.supports
}

function gradleProperties(manifest: AddonManifest, runtimes: Runtime[]): string {
  return `# ${STUDIO_MARKER}
mod_id=${localId(manifest)}
mod_name=${manifest.name}
mod_version=${manifest.version}
mod_group_id=dev.echo.${manifest.namespace}
mod_license=All Rights Reserved
java_language_version=25
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.200
enable_neoforge=${String(runtimes.includes('neoforge'))}
enable_echo_native=${String(runtimes.includes('echo_native'))}
enable_standalone=${String(runtimes.includes('standalone'))}
`
}

function settingsGradle(manifest: AddonManifest): string {
  return `// ${STUDIO_MARKER}
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

rootProject.name = "${localId(manifest)}"
`
}

function buildGradle(manifest: AddonManifest): string {
  return `// ${STUDIO_MARKER}
plugins {
    id "java-library"
    id "maven-publish"
    id "net.neoforged.moddev" version "2.0.141" apply false
    id "idea"
}

def enableNeoForge = providers.gradleProperty("enable_neoforge").orElse("false").get().toBoolean()
def enableNative = providers.gradleProperty("enable_echo_native").orElse("false").get().toBoolean()
def enableStandalone = providers.gradleProperty("enable_standalone").orElse("false").get().toBoolean()

version = providers.gradleProperty("mod_version").get()
group = providers.gradleProperty("mod_group_id").get()

base {
    archivesName = providers.gradleProperty("mod_id").get()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(providers.gradleProperty("java_language_version").orElse("25").get().toInteger())
    }
}

repositories {
    mavenCentral()
    maven { url = uri("https://maven.neoforged.net/releases") }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:5.10.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
}

sourceSets.main.resources {
    srcDir("src/generated/resources")
}

if (enableNeoForge) {
    apply plugin: "net.neoforged.moddev"

    neoForge {
        version = providers.gradleProperty("neo_version").get()
        runs {
            client {
                client()
                systemProperty "neoforge.enabledGameTestNamespaces", providers.gradleProperty("mod_id").get()
            }
            server {
                server()
                programArgument "--nogui"
                systemProperty "neoforge.enabledGameTestNamespaces", providers.gradleProperty("mod_id").get()
            }
            data {
                clientData()
                programArguments.addAll "--mod", providers.gradleProperty("mod_id").get(), "--all",
                    "--output", file("src/generated/resources/").absolutePath,
                    "--existing", file("src/main/resources/").absolutePath
            }
            configureEach {
                systemProperty "forge.logging.markers", "REGISTRIES"
            }
        }
        mods {
            "\${providers.gradleProperty("mod_id").get()}" {
                sourceSet(sourceSets.main)
            }
        }
    }
} else {
    tasks.register("runClient") {
        group = "echo dev"
        description = "Placeholder NeoForge client task. Enable NeoForge in gradle.properties to wire the real client."
        doLast { println "NeoForge is not enabled for this workspace." }
    }
    tasks.register("runServer") {
        group = "echo dev"
        description = "Placeholder server task. Enable NeoForge in gradle.properties to wire the real server."
        doLast { println "NeoForge is not enabled for this workspace." }
    }
    tasks.register("runData") {
        group = "echo dev"
        description = "Placeholder data generation task."
        doLast { println "Data generation is not configured for this workspace." }
    }
}

tasks.register("echoNativePreview") {
    group = "echo dev"
    description = "Starts the native preview lane when the ECHO Native runtime is installed."
    doLast {
        if (!enableNative) throw new GradleException("ECHO Native is not enabled for this workspace.")
        println "Native preview requested for ${manifest.id}. Configure the runtime executable in ECHO Studio Settings."
    }
}

tasks.register("echoStandalonePreview") {
    group = "echo dev"
    description = "Starts the standalone runtime preview lane when the ECHO Standalone runtime is installed."
    doLast {
        if (!enableStandalone) throw new GradleException("Standalone runtime is not enabled for this workspace.")
        println "Standalone preview requested for ${manifest.id}. Configure the runtime executable in ECHO Studio Settings."
    }
}

tasks.register("studioPackage") {
    group = "echo release"
    description = "Studio packaging is run from the ECHO Studio Release page."
    dependsOn("build")
    doLast { println "Use ECHO Studio Release to generate .echo-addon, checksums, and echo-release.json." }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.named("test") {
    useJUnitPlatform()
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
`
}

function javaSource(manifest: AddonManifest): string {
  const pkg = packagePath(manifest).replace(/\//g, '.')
  return `// ${STUDIO_MARKER}
package ${pkg};

/**
 * Local development entrypoint scaffold for ${manifest.name}.
 *
 * Replace this class with your real runtime hooks as the project grows.
 */
public final class ${className(manifest)} {
    public static final String ID = "${manifest.id}";

    private ${className(manifest)}() {
    }

    public static void initialize() {
        System.out.println("Initializing ECHO project: " + ID);
    }
}
`
}

function testSource(manifest: AddonManifest): string {
  const pkg = packagePath(manifest).replace(/\//g, '.')
  return `// ${STUDIO_MARKER}
package ${pkg};

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

final class ${className(manifest)}Test {
    @Test
    void exposesProjectId() {
        assertEquals("${manifest.id}", ${className(manifest)}.ID);
    }
}
`
}

function gradlewBat(): string {
  return `@echo off
REM ${STUDIO_MARKER}
where gradle >nul 2>nul
if errorlevel 1 (
  echo Gradle is not installed or not on PATH.
  echo Install Gradle or replace this bootstrap with a real Gradle wrapper.
  exit /b 1
)
gradle %*
`
}

function gradlewSh(): string {
  return `#!/usr/bin/env sh
# ${STUDIO_MARKER}
if ! command -v gradle >/dev/null 2>&1; then
  echo "Gradle is not installed or not on PATH."
  echo "Install Gradle or replace this bootstrap with a real Gradle wrapper."
  exit 1
fi
gradle "$@"
`
}

function runScript(task: 'run-dev-client' | 'build-local', manifest: AddonManifest): string {
  const command = task === 'run-dev-client' ? './gradlew.bat runClient' : './gradlew.bat build'
  return `# ${STUDIO_MARKER}
Set-Location -LiteralPath $PSScriptRoot\\..
Write-Host "ECHO Studio: ${task === 'run-dev-client' ? 'starting dev client' : 'building local artifacts'} for ${manifest.id}"
${command}
`
}

async function fileStatus(projectPath: string, rel: string): Promise<{ path: string; exists: boolean; generatedByStudio: boolean }> {
  const path = join(projectPath, rel)
  const isThere = await exists(path)
  return {
    path: rel,
    exists: isThere,
    generatedByStudio: isThere ? (await readText(path)).includes(STUDIO_MARKER) : false
  }
}

export async function inspectDevWorkspace(projectPath: string): Promise<DevWorkspaceState> {
  const manifest = await readManifest(projectPath)
  if (!manifest) throw new Error('Missing echo.mod.json')
  const moduleCatalog = await listEchoModules(projectPath)
  const studioStatePath = join(projectPath, '.echo-studio', 'dev-workspace.json')
  const saved = await readText(studioStatePath)
  const parsed = saved ? JSON.parse(saved) as Partial<DevWorkspaceState> : {}
  const files = await Promise.all([
    fileStatus(projectPath, 'echo.mod.json'),
    fileStatus(projectPath, 'META-INF/echo-addon-package.json'),
    fileStatus(projectPath, 'settings.gradle'),
    fileStatus(projectPath, 'build.gradle'),
    fileStatus(projectPath, 'gradle.properties'),
    fileStatus(projectPath, 'gradlew.bat'),
    fileStatus(projectPath, 'gradlew'),
    fileStatus(projectPath, 'src/main/resources/META-INF/echo.mod.json'),
    fileStatus(projectPath, `src/main/java/${packagePath(manifest)}/${className(manifest)}.java`),
    fileStatus(projectPath, `src/test/java/${packagePath(manifest)}/${className(manifest)}Test.java`),
    fileStatus(projectPath, 'release')
  ])
  const hasGradleWrapper = files.some((file) => ['gradlew.bat', 'gradlew'].includes(file.path) && file.exists)
  const gradleReady = files.some((file) => file.path === 'build.gradle' && file.exists) && files.some((file) => file.path === 'settings.gradle' && file.exists)
  const sourceReady = files.some((file) => file.path.startsWith('src/main/java') && file.exists)
  return {
    ready: gradleReady && sourceReady,
    mode: parsed.mode ?? 'visual',
    projectPath,
    gradleReady,
    hasGradleWrapper,
    sourceReady,
    runtimeTargets: parsed.runtimeTargets ?? manifest.runtime.supports,
    files,
    modulePlan: resolveProjectModulePlan(manifest, moduleCatalog.catalog),
    artifacts: await collectArtifacts(projectPath),
    lastSetupAt: parsed.lastSetupAt
  }
}

export async function setupDevWorkspace(projectPath: string, options: DevWorkspaceOptions): Promise<DevSetupResult> {
  const manifest = await readManifest(projectPath)
  if (!manifest) throw new Error('Missing echo.mod.json')
  const runtimes = runtimeTargets(manifest, options)
  const written: string[] = []
  const skipped: string[] = []
  const force = Boolean(options.force)

  await writeIfAllowed(join(projectPath, 'settings.gradle'), settingsGradle(manifest), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'gradle.properties'), gradleProperties(manifest, runtimes), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'build.gradle'), buildGradle(manifest), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'gradlew.bat'), gradlewBat(), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'gradlew'), gradlewSh(), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'META-INF', 'echo-addon-package.json'), JSON.stringify(buildAddonPackageManifest(manifest), null, 2), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'src', 'main', 'resources', 'META-INF', 'echo.mod.json'), JSON.stringify(manifest, null, 2), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'src', 'main', 'java', ...packagePath(manifest).split('/'), `${className(manifest)}.java`), javaSource(manifest), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'src', 'test', 'java', ...packagePath(manifest).split('/'), `${className(manifest)}Test.java`), testSource(manifest), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'scripts', 'run-dev-client.ps1'), runScript('run-dev-client', manifest), force, written, skipped)
  await writeIfAllowed(join(projectPath, 'scripts', 'build-local.ps1'), runScript('build-local', manifest), force, written, skipped)
  await fs.mkdir(join(projectPath, 'release'), { recursive: true })
  await fs.mkdir(join(projectPath, '.echo-studio'), { recursive: true })
  await fs.writeFile(join(projectPath, '.echo-studio', 'dev-workspace.json'), JSON.stringify({
    mode: options.mode,
    runtimeTargets: runtimes,
    lastSetupAt: new Date().toISOString()
  }, null, 2), 'utf8')

  return {
    state: await inspectDevWorkspace(projectPath),
    written: written.map((path) => relative(projectPath, path)),
    skipped: skipped.map((path) => relative(projectPath, path))
  }
}

function gradleCommand(projectPath: string): string {
  if (process.platform === 'win32' && existsSync(join(projectPath, 'gradlew.bat'))) return '.\\gradlew.bat'
  if (existsSync(join(projectPath, 'gradlew'))) return './gradlew'
  return 'gradle'
}

function runShell(command: string, cwd: string, timeoutMs: number): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(command, {
      cwd,
      shell: true,
      windowsHide: true
    })
    let stdout = ''
    let stderr = ''
    const timeout = setTimeout(() => {
      child.kill()
      stderr += `\nCommand timed out after ${timeoutMs}ms.`
    }, timeoutMs)
    child.stdout?.on('data', (chunk) => { stdout += String(chunk) })
    child.stderr?.on('data', (chunk) => { stderr += String(chunk) })
    child.on('close', (code) => {
      clearTimeout(timeout)
      resolve({ exitCode: code ?? 0, stdout, stderr })
    })
    child.on('error', (error) => {
      clearTimeout(timeout)
      resolve({ exitCode: 1, stdout, stderr: `${stderr}\n${error.message}` })
    })
  })
}

export async function runDevTask(projectPath: string, taskId: DevTaskId): Promise<DevTaskRun> {
  const task = DEV_TASKS.find((item) => item.id === taskId)
  if (!task) throw new Error(`Unknown dev task: ${taskId}`)
  const startedAt = new Date().toISOString()

  if (task.id === 'package:local') {
    const command = 'ECHO Studio packageAddon'
    const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
    let result: Awaited<ReturnType<typeof packageAddon>>
    try {
      result = await packageAddon(projectPath)
    } catch (error) {
      const finishedAt = new Date().toISOString()
      await appendTaskLog(logPath, 'error', error instanceof Error ? error.message : String(error))
      await finishTaskLog(logPath, 'failed', finishedAt)
      throw error
    }
    const stdout = `Prepared ${basename(result.zipPath)} with ${result.assetPaths.length} release asset(s).`
    const stderr = result.sdkValidation.issues.join('\n')
    const finishedAt = new Date().toISOString()
    await appendTaskLog(logPath, 'stdout', stdout)
    await appendTaskLog(logPath, 'stderr', stderr)
    await finishTaskLog(logPath, 'completed', finishedAt, 0)
    return {
      taskId,
      status: 'completed',
      command,
      cwd: projectPath,
      logPath,
      stdout,
      stderr,
      startedAt,
      finishedAt,
      artifacts: await collectArtifacts(projectPath)
    }
  }

  const command = `${gradleCommand(projectPath)} ${task.command}`
  const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
  if (task.detached) {
    const child = spawn(command, {
      cwd: projectPath,
      shell: true,
      detached: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true
    })
    child.stdout?.on('data', (chunk) => { void appendTaskLog(logPath, 'stdout', String(chunk)) })
    child.stderr?.on('data', (chunk) => { void appendTaskLog(logPath, 'stderr', String(chunk)) })
    child.on('close', (code) => { void finishTaskLog(logPath, code === 0 ? 'completed' : 'failed', new Date().toISOString(), code ?? undefined) })
    child.on('error', (error) => { void appendTaskLog(logPath, 'error', error.message) })
    child.unref()
    return {
      taskId,
      status: 'started',
      command,
      cwd: projectPath,
      pid: child.pid,
      logPath,
      stdout: `Started ${task.label} as process ${child.pid}.`,
      stderr: '',
      startedAt,
      artifacts: await collectArtifacts(projectPath)
    }
  }

  const result = await runShell(command, projectPath, 180000)
  const status = result.exitCode === 0 ? 'completed' : 'failed'
  const finishedAt = new Date().toISOString()
  await appendTaskLog(logPath, 'stdout', result.stdout)
  await appendTaskLog(logPath, 'stderr', result.stderr)
  await finishTaskLog(logPath, status, finishedAt, result.exitCode)
  return {
    taskId,
    status,
    command,
    cwd: projectPath,
    logPath,
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    startedAt,
    finishedAt,
    artifacts: await collectArtifacts(projectPath)
  }
}

export async function readDevTaskLog(projectPath: string, logPath: string): Promise<string> {
  const root = resolve(projectPath, '.echo-studio', 'logs')
  const target = resolve(logPath)
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    throw new Error('Log path must stay inside the project log folder.')
  }
  const text = await fs.readFile(target, 'utf8')
  return text.length > 200000 ? text.slice(-200000) : text
}
