import { existsSync, promises as fs } from 'fs'
import { basename, dirname, join, relative, resolve, sep } from 'path'
import { spawn } from 'child_process'
import { buildAddonPackageManifest } from '../shared/templates'
import { DEV_TASKS, type DevArtifact, type DevModuleLock, type DevModuleLockStatus, type DevSetupResult, type DevTaskId, type DevTaskRun, type DevWorkspaceFileStatus, type DevWorkspaceMode, type DevWorkspaceOptions, type DevWorkspaceState } from '../shared/devWorkspace'
import { resolveProjectModulePlan, type EchoModuleCatalogResult, type EchoModuleRecord, type ProjectModulePlan } from '../shared/moduleCatalog'
import { buildNeoForgeModsToml } from '../shared/neoforgeMetadata'
import type { AddonManifest, Runtime } from '../shared/types'
import { packageAddon } from './packageService'
import { readManifest } from './fsService'
import { listEchoModules } from './moduleCatalogService'

const STUDIO_MARKER = 'Generated by ECHO Studio'
const GRADLE_VERSION = '9.1.0'
const GRADLE_DISTRIBUTION_URL = `https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip`

async function exists(path: string): Promise<boolean> {
  try {
    await fs.access(path)
    return true
  } catch {
    return false
  }
}

async function readText(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf8')
  } catch {
    return ''
  }
}

async function readModuleLock(path: string): Promise<DevModuleLock | null> {
  try {
    const parsed = JSON.parse(await fs.readFile(path, 'utf8')) as Partial<DevModuleLock>
    return parsed.schemaVersion === 'echo.studio.modules.lock.v1' ? parsed as DevModuleLock : null
  } catch {
    return null
  }
}

async function writeIfAllowed(path: string, content: string, force: boolean, written: string[], skipped: string[]): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true })
  if (!force && await exists(path)) {
    skipped.push(path)
    return
  }
  await fs.writeFile(path, content, 'utf8')
  written.push(path)
}

async function writeGenerated(path: string, content: string, written: string[]): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true })
  await fs.writeFile(path, content, 'utf8')
  written.push(path)
}

function localId(manifest: AddonManifest): string {
  return manifest.id.includes(':') ? manifest.id.split(':')[1] : manifest.id
}

function className(manifest: AddonManifest): string {
  return localId(manifest)
    .split(/[_-]/g)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join('') + 'Module'
}

function packagePath(manifest: AddonManifest): string {
  return `studio/generated/${manifest.namespace.replace(/[^a-z0-9_]/gi, '').toLowerCase()}/${localId(manifest).replace(/[^a-z0-9_]/gi, '').toLowerCase()}`.replace(/\//g, '/')
}

function artifactKind(name: string): DevArtifact['kind'] {
  if (name.endsWith('.echo-addon')) return 'echo-addon'
  if (name.endsWith('.jar')) return 'jar'
  if (name.endsWith('.json')) return 'manifest'
  if (name.endsWith('.sha256')) return 'checksum'
  return 'other'
}

function safeTaskName(taskId: DevTaskId): string {
  return taskId.replace(/[^a-z0-9_-]/gi, '-')
}

function logStamp(date = new Date()): string {
  return date.toISOString().replace(/[:.]/g, '-')
}

async function createTaskLog(projectPath: string, taskId: DevTaskId, command: string, startedAt: string): Promise<string> {
  const dir = join(projectPath, '.echo-studio', 'logs')
  await fs.mkdir(dir, { recursive: true })
  const path = join(dir, `${logStamp(new Date(startedAt))}-${safeTaskName(taskId)}.log`)
  await fs.writeFile(path, [
    `ECHO Studio task: ${taskId}`,
    `Command: ${command}`,
    `Started: ${startedAt}`,
    ''
  ].join('\n'), 'utf8')
  return path
}

async function appendTaskLog(logPath: string, label: string, text: string): Promise<void> {
  if (!text) return
  await fs.appendFile(logPath, `\n[${label}]\n${text}`, 'utf8')
}

async function finishTaskLog(logPath: string, status: DevTaskRun['status'], finishedAt?: string, exitCode?: number): Promise<void> {
  const lines = ['', `[status] ${status}`]
  if (exitCode !== undefined) lines.push(`[exit] ${exitCode}`)
  if (finishedAt) lines.push(`[finished] ${finishedAt}`)
  lines.push('')
  await fs.appendFile(logPath, lines.join('\n'), 'utf8')
}

async function collectArtifacts(projectPath: string): Promise<DevArtifact[]> {
  const roots = [join(projectPath, 'build', 'libs'), join(projectPath, 'release'), join(projectPath, 'exports')]
  const artifacts: DevArtifact[] = []
  for (const root of roots) {
    if (!await exists(root)) continue
    const entries = await fs.readdir(root, { withFileTypes: true })
    for (const entry of entries) {
      if (!entry.isFile()) continue
      const path = join(root, entry.name)
      const stat = await fs.stat(path)
      artifacts.push({
        path,
        name: entry.name,
        kind: artifactKind(entry.name),
        bytes: stat.size,
        modifiedAt: stat.mtimeMs
      })
    }
  }
  return artifacts.sort((a, b) => b.modifiedAt - a.modifiedAt)
}

function runtimeTargets(manifest: AddonManifest, options?: DevWorkspaceOptions): Runtime[] {
  return options?.runtimes?.length ? options.runtimes : manifest.runtime.supports
}

function lockModule(mod: EchoModuleRecord): DevModuleLock['modules'][number] {
  return {
    id: mod.id,
    aliases: mod.aliases,
    name: mod.name,
    role: mod.role,
    kind: mod.kind,
    status: mod.status,
    channel: mod.channel,
    publicApi: mod.publicApi,
    requires: mod.requires,
    optional: mod.optional,
    runtimes: mod.runtimes,
    standaloneReady: mod.standaloneReady,
    launcherVisible: mod.launcherVisible,
    ...(mod.version ? { version: mod.version } : {}),
    ...(mod.source ? { source: mod.source } : {}),
    ...(mod.moduleDir ? { moduleDir: mod.moduleDir } : {}),
    ...(mod.descriptorPath ? { descriptorPath: mod.descriptorPath } : {})
  }
}

function buildModuleLock(manifest: AddonManifest, catalogResult: EchoModuleCatalogResult): DevModuleLock {
  const plan = resolveProjectModulePlan(manifest, catalogResult.catalog)
  return {
    schemaVersion: 'echo.studio.modules.lock.v1',
    generatedBy: STUDIO_MARKER,
    generatedAt: new Date().toISOString(),
    project: {
      id: manifest.id,
      version: manifest.version
    },
    catalog: {
      source: catalogResult.source,
      warnings: catalogResult.warnings,
      ...(catalogResult.indexPath ? { indexPath: catalogResult.indexPath } : {}),
      ...(catalogResult.moduleRoot ? { moduleRoot: catalogResult.moduleRoot } : {}),
      ...(catalogResult.generatedAt ? { generatedAt: catalogResult.generatedAt } : {})
    },
    declared: plan.declared,
    normalizedDeclared: plan.normalizedDeclared,
    moduleCount: plan.closure.length,
    modules: plan.closure.map(lockModule),
    missingRequired: plan.missingRequired.map((mod) => mod.id),
    unknown: plan.unknown
  }
}

function sortedUnique(values: string[]): string[] {
  return Array.from(new Set(values)).sort((a, b) => a.localeCompare(b))
}

function diffIds(expected: string[], actual: string[]): { missing: string[]; extra: string[] } {
  const expectedSet = new Set(expected)
  const actualSet = new Set(actual)
  return {
    missing: expected.filter((id) => !actualSet.has(id)),
    extra: actual.filter((id) => !expectedSet.has(id))
  }
}

async function moduleLockStatus(
  projectPath: string,
  manifest: AddonManifest,
  plan: ProjectModulePlan,
  mode: DevWorkspaceMode
): Promise<DevModuleLockStatus> {
  const studioLockPath = join(projectPath, '.echo-studio', 'modules.lock.json')
  const runtimeLockPath = join(projectPath, 'src', 'generated', 'resources', 'META-INF', 'echo.modules.lock.json')
  const [studioLock, runtimeLock] = await Promise.all([
    readModuleLock(studioLockPath),
    readModuleLock(runtimeLockPath)
  ])
  const runtimeExpected = mode !== 'visual'
  const expectedModuleIds = sortedUnique(plan.closure.map((mod) => mod.id))
  const lockedModuleIds = sortedUnique(studioLock?.modules.map((mod) => mod.id) ?? [])
  const runtimeModuleIds = sortedUnique(runtimeLock?.modules.map((mod) => mod.id) ?? [])
  const studioDiff = diffIds(expectedModuleIds, lockedModuleIds)
  const runtimeDiff = diffIds(expectedModuleIds, runtimeModuleIds)
  const projectMatches = Boolean(
    studioLock &&
    studioLock.project.id === manifest.id &&
    studioLock.project.version === manifest.version
  )
  const runtimeProjectMatches = !runtimeExpected || Boolean(
    runtimeLock &&
    runtimeLock.project.id === manifest.id &&
    runtimeLock.project.version === manifest.version
  )
  const studioUpToDate = Boolean(studioLock) && projectMatches && studioDiff.missing.length === 0 && studioDiff.extra.length === 0
  const runtimeUpToDate = !runtimeExpected || Boolean(runtimeLock) && runtimeProjectMatches && runtimeDiff.missing.length === 0 && runtimeDiff.extra.length === 0
  return {
    schemaVersion: 'echo.studio.modules.lock.status.v1',
    studioLockPath: relative(projectPath, studioLockPath),
    runtimeLockPath: relative(projectPath, runtimeLockPath),
    studioExists: Boolean(studioLock),
    runtimeExists: Boolean(runtimeLock),
    runtimeExpected,
    upToDate: studioUpToDate && runtimeUpToDate,
    runtimeUpToDate,
    projectMatches,
    expectedModuleIds,
    lockedModuleIds,
    runtimeModuleIds,
    missingFromLock: studioDiff.missing,
    extraInLock: studioDiff.extra,
    missingFromRuntimeLock: runtimeDiff.missing,
    extraInRuntimeLock: runtimeDiff.extra,
    lockedProjectId: studioLock?.project.id,
    lockedProjectVersion: studioLock?.project.version,
    generatedAt: studioLock?.generatedAt
  }
}

function gradleProperties(manifest: AddonManifest, runtimes: Runtime[]): string {
  return `# ${STUDIO_MARKER}
mod_id=${localId(manifest)}
mod_name=${manifest.name}
mod_version=${manifest.version}
mod_group_id=dev.echo.${manifest.namespace}
mod_license=All Rights Reserved
java_language_version=25
echo_gradle_version=${GRADLE_VERSION}
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.200
enable_neoforge=${String(runtimes.includes('neoforge'))}
enable_echo_native=${String(runtimes.includes('echo_native'))}
enable_standalone=${String(runtimes.includes('standalone'))}
`
}

function settingsGradle(manifest: AddonManifest): string {
  return `// ${STUDIO_MARKER}
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { url = uri("https://maven.neoforged.net/releases") }
    }
}

rootProject.name = "${localId(manifest)}"
`
}

function buildGradle(manifest: AddonManifest): string {
  return `// ${STUDIO_MARKER}
plugins {
    id "java-library"
    id "maven-publish"
    id "net.neoforged.moddev" version "2.0.141" apply false
    id "idea"
}

def enableNeoForge = providers.gradleProperty("enable_neoforge").orElse("false").get().toBoolean()
def enableNative = providers.gradleProperty("enable_echo_native").orElse("false").get().toBoolean()
def enableStandalone = providers.gradleProperty("enable_standalone").orElse("false").get().toBoolean()

version = providers.gradleProperty("mod_version").get()
group = providers.gradleProperty("mod_group_id").get()

base {
    archivesName = providers.gradleProperty("mod_id").get()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(providers.gradleProperty("java_language_version").orElse("25").get().toInteger())
    }
}

repositories {
    mavenCentral()
    maven { url = uri("https://maven.neoforged.net/releases") }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:5.10.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
}

sourceSets.main.resources {
    srcDir("src/generated/resources")
}

if (enableNeoForge) {
    apply plugin: "net.neoforged.moddev"

    neoForge {
        version = providers.gradleProperty("neo_version").get()
        runs {
            client {
                client()
                systemProperty "neoforge.enabledGameTestNamespaces", providers.gradleProperty("mod_id").get()
            }
            server {
                server()
                programArgument "--nogui"
                systemProperty "neoforge.enabledGameTestNamespaces", providers.gradleProperty("mod_id").get()
            }
            data {
                clientData()
                programArguments.addAll "--mod", providers.gradleProperty("mod_id").get(), "--all",
                    "--output", file("src/generated/resources/").absolutePath,
                    "--existing", file("src/main/resources/").absolutePath
            }
            configureEach {
                systemProperty "forge.logging.markers", "REGISTRIES"
            }
        }
        mods {
            "\${providers.gradleProperty("mod_id").get()}" {
                sourceSet(sourceSets.main)
            }
        }
    }
} else {
    tasks.register("runClient") {
        group = "echo dev"
        description = "Placeholder NeoForge client task. Enable NeoForge in gradle.properties to wire the real client."
        doLast { println "NeoForge is not enabled for this workspace." }
    }
    tasks.register("runServer") {
        group = "echo dev"
        description = "Placeholder server task. Enable NeoForge in gradle.properties to wire the real server."
        doLast { println "NeoForge is not enabled for this workspace." }
    }
    tasks.register("runData") {
        group = "echo dev"
        description = "Placeholder data generation task."
        doLast { println "Data generation is not configured for this workspace." }
    }
}

tasks.register("echoNativePreview") {
    group = "echo dev"
    description = "Starts the native preview lane when the ECHO Native runtime is installed."
    doLast {
        if (!enableNative) throw new GradleException("ECHO Native is not enabled for this workspace.")
        println "Native preview requested for ${manifest.id}. Configure the runtime executable in ECHO Studio Settings."
    }
}

tasks.register("echoStandalonePreview") {
    group = "echo dev"
    description = "Starts the standalone runtime preview lane when the ECHO Standalone runtime is installed."
    doLast {
        if (!enableStandalone) throw new GradleException("Standalone runtime is not enabled for this workspace.")
        println "Standalone preview requested for ${manifest.id}. Configure the runtime executable in ECHO Studio Settings."
    }
}

tasks.register("studioPackage") {
    group = "echo release"
    description = "Studio packaging is run from the ECHO Studio Release page."
    dependsOn("build")
    doLast { println "Use ECHO Studio Release to generate .echo-addon, checksums, and echo-release.json." }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.named("test") {
    useJUnitPlatform()
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
`
}

function javaSource(manifest: AddonManifest): string {
  const pkg = packagePath(manifest).replace(/\//g, '.')
  return `// ${STUDIO_MARKER}
package ${pkg};

/**
 * Local development entrypoint scaffold for ${manifest.name}.
 *
 * Replace this class with your real runtime hooks as the project grows.
 */
public final class ${className(manifest)} {
    public static final String ID = "${manifest.id}";

    private ${className(manifest)}() {
    }

    public static void initialize() {
        System.out.println("Initializing ECHO project: " + ID);
    }
}
`
}

function testSource(manifest: AddonManifest): string {
  const pkg = packagePath(manifest).replace(/\//g, '.')
  return `// ${STUDIO_MARKER}
package ${pkg};

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

final class ${className(manifest)}Test {
    @Test
    void exposesProjectId() {
        assertEquals("${manifest.id}", ${className(manifest)}.ID);
    }
}
`
}

function gradlewBat(): string {
  return `@echo off
REM ${STUDIO_MARKER}
setlocal
set "SCRIPT_DIR=%~dp0"
pushd "%SCRIPT_DIR%" >nul
set "GRADLE_VERSION=${GRADLE_VERSION}"
set "GRADLE_DIST_URL=${GRADLE_DISTRIBUTION_URL}"
set "GRADLE_CACHE=%SCRIPT_DIR%.gradle\\studio"
set "GRADLE_HOME=%GRADLE_CACHE%\\gradle-%GRADLE_VERSION%"
set "GRADLE_BIN=%GRADLE_HOME%\\bin\\gradle.bat"

if not exist "%GRADLE_BIN%" (
  echo ECHO Studio: preparing Gradle %GRADLE_VERSION%...
  powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $url=$env:GRADLE_DIST_URL; $cache=$env:GRADLE_CACHE; $zip=Join-Path $cache ('gradle-' + $env:GRADLE_VERSION + '-bin.zip'); New-Item -ItemType Directory -Force $cache | Out-Null; if (!(Test-Path $zip)) { Invoke-WebRequest -Uri $url -OutFile $zip }; Expand-Archive -Path $zip -DestinationPath $cache -Force"
  if errorlevel 1 (
    popd >nul
    exit /b 1
  )
)
"%GRADLE_BIN%" %*
set "EXIT_CODE=%errorlevel%"
popd >nul
exit /b %EXIT_CODE%
`
}

function gradlewSh(): string {
  return `#!/usr/bin/env sh
# ${STUDIO_MARKER}
set -eu

APP_HOME=$(CDPATH= cd "$(dirname "$0")" && pwd)
cd "$APP_HOME"

GRADLE_VERSION="${GRADLE_VERSION}"
GRADLE_DIST_URL="${GRADLE_DISTRIBUTION_URL}"
GRADLE_CACHE="$APP_HOME/.gradle/studio"
GRADLE_HOME="$GRADLE_CACHE/gradle-$GRADLE_VERSION"
GRADLE_BIN="$GRADLE_HOME/bin/gradle"
GRADLE_ZIP="$GRADLE_CACHE/gradle-$GRADLE_VERSION-bin.zip"

if [ ! -x "$GRADLE_BIN" ]; then
  echo "ECHO Studio: preparing Gradle $GRADLE_VERSION..."
  mkdir -p "$GRADLE_CACHE"
  if [ ! -f "$GRADLE_ZIP" ]; then
    if command -v curl >/dev/null 2>&1; then
      curl -L "$GRADLE_DIST_URL" -o "$GRADLE_ZIP"
    elif command -v wget >/dev/null 2>&1; then
      wget -O "$GRADLE_ZIP" "$GRADLE_DIST_URL"
    else
      echo "curl or wget is required to download Gradle." >&2
      exit 1
    fi
  fi
  if ! command -v unzip >/dev/null 2>&1; then
    echo "unzip is required to expand Gradle." >&2
    exit 1
  fi
  unzip -oq "$GRADLE_ZIP" -d "$GRADLE_CACHE"
  chmod +x "$GRADLE_BIN" || true
fi

exec "$GRADLE_BIN" "$@"
`
}

function runScript(task: 'run-dev-client' | 'build-local', manifest: AddonManifest): string {
  const command = task === 'run-dev-client' ? './gradlew.bat runClient' : './gradlew.bat build'
  return `# ${STUDIO_MARKER}
Set-Location -LiteralPath $PSScriptRoot\\..
Write-Host "ECHO Studio: ${task === 'run-dev-client' ? 'starting dev client' : 'building local artifacts'} for ${manifest.id}"
${command}
`
}

function releaseChecklist(manifest: AddonManifest): string {
  return `# ${STUDIO_MARKER}
# Local Release Checklist

Project: ${manifest.name}
ID: ${manifest.id}
Version: ${manifest.version}

1. Run Gradle tests from ECHO Studio.
2. Run Package Local Release from ECHO Studio.
3. Review release/echo-release.json and release/checksums.sha256.
4. Create the GitHub draft from Publish Assistant when the local package is ready.
5. Submit release-index-handoff.json for Release Index ingestion review.
`
}

function expectedModes(rel: string): DevWorkspaceMode[] {
  if (rel === 'echo.mod.json' || rel === '.echo-studio/dev-workspace.json' || rel === '.echo-studio/modules.lock.json') return ['visual', 'gradle', 'full']
  if (
    [
      'settings.gradle',
      'build.gradle',
      'gradle.properties',
      'gradlew.bat',
      'gradlew',
      'src/main/resources/META-INF/echo.mod.json',
      'src/generated/resources/META-INF/echo.modules.lock.json'
    ].includes(rel) ||
    rel.startsWith('src/main/java/') ||
    rel.startsWith('src/test/java/') ||
    rel.startsWith('scripts/')
  ) {
    return ['gradle', 'full']
  }
  if (rel === 'META-INF/echo-addon-package.json' || rel === 'release' || rel === '.echo-studio/release-checklist.md') {
    return ['full']
  }
  return []
}

function isExpectedForMode(rel: string, mode: DevWorkspaceMode, runtimes: Runtime[]): boolean {
  if (rel === 'src/generated/resources/META-INF/neoforge.mods.toml') {
    return mode !== 'visual' && runtimes.includes('neoforge')
  }
  return expectedModes(rel).includes(mode)
}

async function fileStatus(projectPath: string, rel: string, mode: DevWorkspaceMode, runtimes: Runtime[]): Promise<DevWorkspaceFileStatus> {
  const path = join(projectPath, rel)
  const isThere = await exists(path)
  return {
    path: rel,
    exists: isThere,
    generatedByStudio: isThere ? (await readText(path)).includes(STUDIO_MARKER) : false,
    expected: isExpectedForMode(rel, mode, runtimes)
  }
}

export async function inspectDevWorkspace(projectPath: string): Promise<DevWorkspaceState> {
  const manifest = await readManifest(projectPath)
  if (!manifest) throw new Error('Missing echo.mod.json')
  const moduleCatalog = await listEchoModules(projectPath)
  const studioStatePath = join(projectPath, '.echo-studio', 'dev-workspace.json')
  const saved = await readText(studioStatePath)
  const parsed = saved ? JSON.parse(saved) as Partial<DevWorkspaceState> : {}
  const mode = parsed.mode ?? 'visual'
  const runtimes = parsed.runtimeTargets ?? manifest.runtime.supports
  const javaPath = `src/main/java/${packagePath(manifest)}/${className(manifest)}.java`
  const testPath = `src/test/java/${packagePath(manifest)}/${className(manifest)}Test.java`
  const files = await Promise.all([
    fileStatus(projectPath, 'echo.mod.json', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/dev-workspace.json', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/modules.lock.json', mode, runtimes),
    fileStatus(projectPath, 'META-INF/echo-addon-package.json', mode, runtimes),
    fileStatus(projectPath, 'settings.gradle', mode, runtimes),
    fileStatus(projectPath, 'build.gradle', mode, runtimes),
    fileStatus(projectPath, 'gradle.properties', mode, runtimes),
    fileStatus(projectPath, 'gradlew.bat', mode, runtimes),
    fileStatus(projectPath, 'gradlew', mode, runtimes),
    fileStatus(projectPath, 'src/main/resources/META-INF/echo.mod.json', mode, runtimes),
    fileStatus(projectPath, 'src/generated/resources/META-INF/echo.modules.lock.json', mode, runtimes),
    fileStatus(projectPath, 'src/generated/resources/META-INF/neoforge.mods.toml', mode, runtimes),
    fileStatus(projectPath, javaPath, mode, runtimes),
    fileStatus(projectPath, testPath, mode, runtimes),
    fileStatus(projectPath, 'scripts/run-dev-client.ps1', mode, runtimes),
    fileStatus(projectPath, 'scripts/build-local.ps1', mode, runtimes),
    fileStatus(projectPath, '.echo-studio/release-checklist.md', mode, runtimes),
    fileStatus(projectPath, 'release', mode, runtimes)
  ])
  const modulePlan = resolveProjectModulePlan(manifest, moduleCatalog.catalog)
  const hasGradleWrapper = files.some((file) => ['gradlew.bat', 'gradlew'].includes(file.path) && file.exists)
  const gradleReady = files.some((file) => file.path === 'build.gradle' && file.exists) && files.some((file) => file.path === 'settings.gradle' && file.exists)
  const sourceReady = files.some((file) => file.path.startsWith('src/main/java') && file.exists)
  const expectedReady = files.filter((file) => file.expected).every((file) => file.exists)
  const lockStatus = await moduleLockStatus(projectPath, manifest, modulePlan, mode)
  return {
    ready: Boolean(parsed.lastSetupAt) && expectedReady && lockStatus.upToDate,
    mode,
    projectPath,
    gradleReady,
    hasGradleWrapper,
    sourceReady,
    runtimeTargets: runtimes,
    files,
    modulePlan,
    moduleLock: lockStatus,
    artifacts: await collectArtifacts(projectPath),
    lastSetupAt: parsed.lastSetupAt
  }
}

export async function setupDevWorkspace(projectPath: string, options: DevWorkspaceOptions): Promise<DevSetupResult> {
  const manifest = await readManifest(projectPath)
  if (!manifest) throw new Error('Missing echo.mod.json')
  const runtimes = runtimeTargets(manifest, options)
  const moduleCatalog = await listEchoModules(projectPath)
  const moduleLock = buildModuleLock(manifest, moduleCatalog)
  const moduleLockJson = `${JSON.stringify(moduleLock, null, 2)}\n`
  const written: string[] = []
  const skipped: string[] = []
  const force = Boolean(options.force)

  await fs.mkdir(join(projectPath, '.echo-studio'), { recursive: true })
  await writeGenerated(join(projectPath, '.echo-studio', 'modules.lock.json'), moduleLockJson, written)

  if (options.mode === 'gradle' || options.mode === 'full') {
    await writeIfAllowed(join(projectPath, 'settings.gradle'), settingsGradle(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'gradle.properties'), gradleProperties(manifest, runtimes), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'build.gradle'), buildGradle(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'gradlew.bat'), gradlewBat(), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'gradlew'), gradlewSh(), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'src', 'main', 'resources', 'META-INF', 'echo.mod.json'), JSON.stringify(manifest, null, 2), force, written, skipped)
    await writeGenerated(join(projectPath, 'src', 'generated', 'resources', 'META-INF', 'echo.modules.lock.json'), moduleLockJson, written)
    if (runtimes.includes('neoforge')) {
      await writeGenerated(join(projectPath, 'src', 'generated', 'resources', 'META-INF', 'neoforge.mods.toml'), buildNeoForgeModsToml(manifest), written)
    }
    await writeIfAllowed(join(projectPath, 'src', 'main', 'java', ...packagePath(manifest).split('/'), `${className(manifest)}.java`), javaSource(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'src', 'test', 'java', ...packagePath(manifest).split('/'), `${className(manifest)}Test.java`), testSource(manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'scripts', 'run-dev-client.ps1'), runScript('run-dev-client', manifest), force, written, skipped)
    await writeIfAllowed(join(projectPath, 'scripts', 'build-local.ps1'), runScript('build-local', manifest), force, written, skipped)
  }

  if (options.mode === 'full') {
    await writeIfAllowed(join(projectPath, 'META-INF', 'echo-addon-package.json'), JSON.stringify(buildAddonPackageManifest(manifest), null, 2), force, written, skipped)
    const releaseDir = join(projectPath, 'release')
    const releaseExists = await exists(releaseDir)
    await fs.mkdir(releaseDir, { recursive: true })
    if (releaseExists && !force) skipped.push(releaseDir)
    else written.push(releaseDir)
    await writeIfAllowed(join(projectPath, '.echo-studio', 'release-checklist.md'), releaseChecklist(manifest), force, written, skipped)
  }

  const statePath = join(projectPath, '.echo-studio', 'dev-workspace.json')
  await fs.writeFile(statePath, JSON.stringify({
    mode: options.mode,
    runtimeTargets: runtimes,
    lastSetupAt: new Date().toISOString()
  }, null, 2), 'utf8')
  written.push(statePath)

  return {
    state: await inspectDevWorkspace(projectPath),
    written: written.map((path) => relative(projectPath, path)),
    skipped: skipped.map((path) => relative(projectPath, path))
  }
}

function gradleCommand(projectPath: string): string {
  if (process.platform === 'win32' && existsSync(join(projectPath, 'gradlew.bat'))) return '.\\gradlew.bat'
  if (existsSync(join(projectPath, 'gradlew'))) return './gradlew'
  return 'gradle'
}

function runShell(command: string, cwd: string, timeoutMs: number): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(command, {
      cwd,
      shell: true,
      windowsHide: true
    })
    let stdout = ''
    let stderr = ''
    const timeout = setTimeout(() => {
      child.kill()
      stderr += `\nCommand timed out after ${timeoutMs}ms.`
    }, timeoutMs)
    child.stdout?.on('data', (chunk) => { stdout += String(chunk) })
    child.stderr?.on('data', (chunk) => { stderr += String(chunk) })
    child.on('close', (code) => {
      clearTimeout(timeout)
      resolve({ exitCode: code ?? 0, stdout, stderr })
    })
    child.on('error', (error) => {
      clearTimeout(timeout)
      resolve({ exitCode: 1, stdout, stderr: `${stderr}\n${error.message}` })
    })
  })
}

export async function runDevTask(projectPath: string, taskId: DevTaskId): Promise<DevTaskRun> {
  const task = DEV_TASKS.find((item) => item.id === taskId)
  if (!task) throw new Error(`Unknown dev task: ${taskId}`)
  const startedAt = new Date().toISOString()

  if (task.id === 'package:local') {
    const command = 'ECHO Studio packageAddon'
    const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
    let result: Awaited<ReturnType<typeof packageAddon>>
    try {
      result = await packageAddon(projectPath, await inspectDevWorkspace(projectPath))
    } catch (error) {
      const finishedAt = new Date().toISOString()
      await appendTaskLog(logPath, 'error', error instanceof Error ? error.message : String(error))
      await finishTaskLog(logPath, 'failed', finishedAt)
      throw error
    }
    const stdout = `Prepared ${basename(result.zipPath)} with ${result.assetPaths.length} release asset(s).`
    const stderr = result.sdkValidation.issues.join('\n')
    const finishedAt = new Date().toISOString()
    await appendTaskLog(logPath, 'stdout', stdout)
    await appendTaskLog(logPath, 'stderr', stderr)
    await finishTaskLog(logPath, 'completed', finishedAt, 0)
    return {
      taskId,
      status: 'completed',
      command,
      cwd: projectPath,
      logPath,
      stdout,
      stderr,
      startedAt,
      finishedAt,
      artifacts: await collectArtifacts(projectPath)
    }
  }

  const command = `${gradleCommand(projectPath)} ${task.command}`
  const logPath = await createTaskLog(projectPath, taskId, command, startedAt)
  if (task.detached) {
    const child = spawn(command, {
      cwd: projectPath,
      shell: true,
      detached: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true
    })
    child.stdout?.on('data', (chunk) => { void appendTaskLog(logPath, 'stdout', String(chunk)) })
    child.stderr?.on('data', (chunk) => { void appendTaskLog(logPath, 'stderr', String(chunk)) })
    child.on('close', (code) => { void finishTaskLog(logPath, code === 0 ? 'completed' : 'failed', new Date().toISOString(), code ?? undefined) })
    child.on('error', (error) => { void appendTaskLog(logPath, 'error', error.message) })
    child.unref()
    return {
      taskId,
      status: 'started',
      command,
      cwd: projectPath,
      pid: child.pid,
      logPath,
      stdout: `Started ${task.label} as process ${child.pid}.`,
      stderr: '',
      startedAt,
      artifacts: await collectArtifacts(projectPath)
    }
  }

  const result = await runShell(command, projectPath, 180000)
  const status = result.exitCode === 0 ? 'completed' : 'failed'
  const finishedAt = new Date().toISOString()
  await appendTaskLog(logPath, 'stdout', result.stdout)
  await appendTaskLog(logPath, 'stderr', result.stderr)
  await finishTaskLog(logPath, status, finishedAt, result.exitCode)
  return {
    taskId,
    status,
    command,
    cwd: projectPath,
    logPath,
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    startedAt,
    finishedAt,
    artifacts: await collectArtifacts(projectPath)
  }
}

export async function readDevTaskLog(projectPath: string, logPath: string): Promise<string> {
  const root = resolve(projectPath, '.echo-studio', 'logs')
  const target = resolve(logPath)
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    throw new Error('Log path must stay inside the project log folder.')
  }
  const text = await fs.readFile(target, 'utf8')
  return text.length > 200000 ? text.slice(-200000) : text
}
